# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Wed Mar 12 15:36:42 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1274, 986)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 1251, 921))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayoutWidget = QtGui.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 711, 72))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayoutFileSelect = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutFileSelect.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayoutFileSelect.setMargin(0)
        self.gridLayoutFileSelect.setObjectName(_fromUtf8("gridLayoutFileSelect"))
        self.lineEditInput = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditInput.setFont(font)
        self.lineEditInput.setObjectName(_fromUtf8("lineEditInput"))
        self.gridLayoutFileSelect.addWidget(self.lineEditInput, 0, 1, 1, 1)
        self.lineEditOutput = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditOutput.setFont(font)
        self.lineEditOutput.setObjectName(_fromUtf8("lineEditOutput"))
        self.gridLayoutFileSelect.addWidget(self.lineEditOutput, 1, 1, 1, 1)
        self.pushButtonInput = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonInput.setFont(font)
        self.pushButtonInput.setObjectName(_fromUtf8("pushButtonInput"))
        self.gridLayoutFileSelect.addWidget(self.pushButtonInput, 0, 0, 1, 1)
        self.pushButtonOutput = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonOutput.setFont(font)
        self.pushButtonOutput.setObjectName(_fromUtf8("pushButtonOutput"))
        self.gridLayoutFileSelect.addWidget(self.pushButtonOutput, 1, 0, 1, 1)
        self.groupBoxOPTOnly = QtGui.QGroupBox(self.frame)
        self.groupBoxOPTOnly.setGeometry(QtCore.QRect(20, 580, 1221, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxOPTOnly.setFont(font)
        self.groupBoxOPTOnly.setStyleSheet(_fromUtf8("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;    \n"
"    background:url(:/assets/subWindowBackground);\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;   \n"
"}"))
        self.groupBoxOPTOnly.setCheckable(True)
        self.groupBoxOPTOnly.setChecked(False)
        self.groupBoxOPTOnly.setObjectName(_fromUtf8("groupBoxOPTOnly"))
        self.formLayoutWidget_5 = QtGui.QWidget(self.groupBoxOPTOnly)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(11, 32, 261, 224))
        self.formLayoutWidget_5.setObjectName(_fromUtf8("formLayoutWidget_5"))
        self.formLayoutCh1 = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayoutCh1.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayoutCh1.setMargin(0)
        self.formLayoutCh1.setObjectName(_fromUtf8("formLayoutCh1"))
        self.checkBox_4 = QtGui.QCheckBox(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.formLayoutCh1.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox_4)
        self.lineEdit_15 = QtGui.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.formLayoutCh1.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_15)
        self.pushButton_9 = QtGui.QPushButton(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.formLayoutCh1.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButton_9)
        self.lineEdit_16 = QtGui.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.formLayoutCh1.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_16)
        self.pushButton_10 = QtGui.QPushButton(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.formLayoutCh1.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_10)
        self.lineEdit_17 = QtGui.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.formLayoutCh1.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_17)
        self.pushButton_11 = QtGui.QPushButton(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.formLayoutCh1.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButton_11)
        self.lineEdit_18 = QtGui.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.formLayoutCh1.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_18)
        self.pushButton_12 = QtGui.QPushButton(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.formLayoutCh1.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButton_12)
        self.lineEdit_19 = QtGui.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.formLayoutCh1.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_19)
        self.comboBox_3 = QtGui.QComboBox(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.formLayoutCh1.setWidget(5, QtGui.QFormLayout.LabelRole, self.comboBox_3)
        self.formLayoutWidget_6 = QtGui.QWidget(self.groupBoxOPTOnly)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(290, 32, 261, 224))
        self.formLayoutWidget_6.setObjectName(_fromUtf8("formLayoutWidget_6"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.checkBox_5 = QtGui.QCheckBox(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox_5)
        self.lineEdit_20 = QtGui.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_20)
        self.pushButton_13 = QtGui.QPushButton(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButton_13)
        self.lineEdit_21 = QtGui.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_21)
        self.pushButton_14 = QtGui.QPushButton(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_14)
        self.lineEdit_22 = QtGui.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_22)
        self.pushButton_15 = QtGui.QPushButton(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButton_15)
        self.lineEdit_23 = QtGui.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_23)
        self.pushButton_16 = QtGui.QPushButton(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButton_16)
        self.lineEdit_24 = QtGui.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_24)
        self.comboBox_4 = QtGui.QComboBox(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.comboBox_4)
        self.formLayoutWidget_7 = QtGui.QWidget(self.groupBoxOPTOnly)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(570, 32, 261, 224))
        self.formLayoutWidget_7.setObjectName(_fromUtf8("formLayoutWidget_7"))
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.checkBox_6 = QtGui.QCheckBox(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox_6)
        self.lineEdit_25 = QtGui.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_25)
        self.pushButton_17 = QtGui.QPushButton(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButton_17)
        self.lineEdit_26 = QtGui.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_26)
        self.pushButton_18 = QtGui.QPushButton(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_18)
        self.lineEdit_27 = QtGui.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_27.setFont(font)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_27)
        self.pushButton_19 = QtGui.QPushButton(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButton_19)
        self.lineEdit_28 = QtGui.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_28)
        self.pushButton_20 = QtGui.QPushButton(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButton_20)
        self.lineEdit_29 = QtGui.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_29.setFont(font)
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_29)
        self.comboBox_5 = QtGui.QComboBox(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.LabelRole, self.comboBox_5)
        self.formLayoutWidget_8 = QtGui.QWidget(self.groupBoxOPTOnly)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(850, 32, 261, 224))
        self.formLayoutWidget_8.setObjectName(_fromUtf8("formLayoutWidget_8"))
        self.formLayout_6 = QtGui.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setMargin(0)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.checkBox_7 = QtGui.QCheckBox(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox_7)
        self.lineEdit_30 = QtGui.QLineEdit(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_30.setFont(font)
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_30)
        self.pushButton_21 = QtGui.QPushButton(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButton_21)
        self.lineEdit_31 = QtGui.QLineEdit(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_31.setFont(font)
        self.lineEdit_31.setObjectName(_fromUtf8("lineEdit_31"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_31)
        self.pushButton_22 = QtGui.QPushButton(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_22)
        self.lineEdit_32 = QtGui.QLineEdit(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_32.setFont(font)
        self.lineEdit_32.setObjectName(_fromUtf8("lineEdit_32"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_32)
        self.pushButton_23 = QtGui.QPushButton(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButton_23)
        self.lineEdit_33 = QtGui.QLineEdit(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_33.setFont(font)
        self.lineEdit_33.setObjectName(_fromUtf8("lineEdit_33"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_33)
        self.pushButton_24 = QtGui.QPushButton(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButton_24)
        self.lineEdit_34 = QtGui.QLineEdit(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_34.setFont(font)
        self.lineEdit_34.setObjectName(_fromUtf8("lineEdit_34"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_34)
        self.comboBox_6 = QtGui.QComboBox(self.formLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.LabelRole, self.comboBox_6)
        self.groupBoxModality = QtGui.QGroupBox(self.frame)
        self.groupBoxModality.setGeometry(QtCore.QRect(740, 20, 501, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxModality.setFont(font)
        self.groupBoxModality.setStyleSheet(_fromUtf8("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;    \n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;   \n"
"}"))
        self.groupBoxModality.setObjectName(_fromUtf8("groupBoxModality"))
        self.radioButtonuCT = QtGui.QRadioButton(self.groupBoxModality)
        self.radioButtonuCT.setGeometry(QtCore.QRect(9, 30, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonuCT.setFont(font)
        self.radioButtonuCT.setChecked(True)
        self.radioButtonuCT.setObjectName(_fromUtf8("radioButtonuCT"))
        self.radioButtonOPT = QtGui.QRadioButton(self.groupBoxModality)
        self.radioButtonOPT.setGeometry(QtCore.QRect(119, 30, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonOPT.setFont(font)
        self.radioButtonOPT.setObjectName(_fromUtf8("radioButtonOPT"))
        self.groupBoxID = QtGui.QGroupBox(self.frame)
        self.groupBoxID.setGeometry(QtCore.QRect(20, 200, 711, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxID.setFont(font)
        self.groupBoxID.setStyleSheet(_fromUtf8("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;    \n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;   \n"
"}"))
        self.groupBoxID.setObjectName(_fromUtf8("groupBoxID"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBoxID)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(11, 28, 691, 34))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayoutIDs = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayoutIDs.setMargin(0)
        self.gridLayoutIDs.setObjectName(_fromUtf8("gridLayoutIDs"))
        self.labelAge = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelAge.setFont(font)
        self.labelAge.setObjectName(_fromUtf8("labelAge"))
        self.gridLayoutIDs.addWidget(self.labelAge, 0, 4, 1, 1)
        self.lineEditGroup = QtGui.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditGroup.setFont(font)
        self.lineEditGroup.setObjectName(_fromUtf8("lineEditGroup"))
        self.gridLayoutIDs.addWidget(self.lineEditGroup, 0, 3, 1, 1)
        self.lineEditDate = QtGui.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditDate.sizePolicy().hasHeightForWidth())
        self.lineEditDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditDate.setFont(font)
        self.lineEditDate.setText(_fromUtf8(""))
        self.lineEditDate.setObjectName(_fromUtf8("lineEditDate"))
        self.gridLayoutIDs.addWidget(self.lineEditDate, 0, 1, 1, 1)
        self.lineEditAge = QtGui.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditAge.setFont(font)
        self.lineEditAge.setObjectName(_fromUtf8("lineEditAge"))
        self.gridLayoutIDs.addWidget(self.lineEditAge, 0, 5, 1, 1)
        self.labelDate = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelDate.setFont(font)
        self.labelDate.setObjectName(_fromUtf8("labelDate"))
        self.gridLayoutIDs.addWidget(self.labelDate, 0, 0, 1, 1)
        self.labelGroup = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelGroup.setFont(font)
        self.labelGroup.setObjectName(_fromUtf8("labelGroup"))
        self.gridLayoutIDs.addWidget(self.labelGroup, 0, 2, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBoxID)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 691, 34))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayoutName = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayoutName.setMargin(0)
        self.gridLayoutName.setObjectName(_fromUtf8("gridLayoutName"))
        self.labelName = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelName.setFont(font)
        self.labelName.setObjectName(_fromUtf8("labelName"))
        self.gridLayoutName.addWidget(self.labelName, 0, 0, 1, 1)
        self.lineEditName = QtGui.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditName.setFont(font)
        self.lineEditName.setReadOnly(False)
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.gridLayoutName.addWidget(self.lineEditName, 0, 1, 1, 1)
        self.gridLayoutWidget_5 = QtGui.QWidget(self.groupBoxID)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(11, 64, 691, 34))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayoutIDs_2 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayoutIDs_2.setMargin(0)
        self.gridLayoutIDs_2.setObjectName(_fromUtf8("gridLayoutIDs_2"))
        self.labelLitter = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelLitter.setFont(font)
        self.labelLitter.setObjectName(_fromUtf8("labelLitter"))
        self.gridLayoutIDs_2.addWidget(self.labelLitter, 0, 0, 1, 1)
        self.lineEditLitter = QtGui.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditLitter.setFont(font)
        self.lineEditLitter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditLitter.setText(_fromUtf8(""))
        self.lineEditLitter.setObjectName(_fromUtf8("lineEditLitter"))
        self.gridLayoutIDs_2.addWidget(self.lineEditLitter, 0, 1, 1, 1)
        self.labelSex = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelSex.setFont(font)
        self.labelSex.setObjectName(_fromUtf8("labelSex"))
        self.gridLayoutIDs_2.addWidget(self.labelSex, 0, 4, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayoutIDs_2.addWidget(self.lineEdit_2, 0, 5, 1, 1)
        self.lineEditZygosity = QtGui.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditZygosity.setFont(font)
        self.lineEditZygosity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditZygosity.setObjectName(_fromUtf8("lineEditZygosity"))
        self.gridLayoutIDs_2.addWidget(self.lineEditZygosity, 0, 3, 1, 1)
        self.labelZygosity = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelZygosity.setFont(font)
        self.labelZygosity.setObjectName(_fromUtf8("labelZygosity"))
        self.gridLayoutIDs_2.addWidget(self.labelZygosity, 0, 2, 1, 1)
        self.groupBoxOptions = QtGui.QGroupBox(self.frame)
        self.groupBoxOptions.setGeometry(QtCore.QRect(740, 110, 501, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxOptions.setFont(font)
        self.groupBoxOptions.setStyleSheet(_fromUtf8("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;    \n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;   \n"
"}"))
        self.groupBoxOptions.setObjectName(_fromUtf8("groupBoxOptions"))
        self.label_5 = QtGui.QLabel(self.groupBoxOptions)
        self.label_5.setGeometry(QtCore.QRect(9, 33, 101, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_13 = QtGui.QLabel(self.groupBoxOptions)
        self.label_13.setGeometry(QtCore.QRect(10, 139, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.checkBoxMovie_2 = QtGui.QCheckBox(self.groupBoxOptions)
        self.checkBoxMovie_2.setGeometry(QtCore.QRect(155, 139, 136, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxMovie_2.setFont(font)
        self.checkBoxMovie_2.setObjectName(_fromUtf8("checkBoxMovie_2"))
        self.label_14 = QtGui.QLabel(self.groupBoxOptions)
        self.label_14.setGeometry(QtCore.QRect(10, 57, 137, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEditX = QtGui.QLineEdit(self.groupBoxOptions)
        self.lineEditX.setEnabled(True)
        self.lineEditX.setGeometry(QtCore.QRect(155, 94, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditX.setFont(font)
        self.lineEditX.setReadOnly(False)
        self.lineEditX.setObjectName(_fromUtf8("lineEditX"))
        self.lineEditY = QtGui.QLineEdit(self.groupBoxOptions)
        self.lineEditY.setEnabled(True)
        self.lineEditY.setGeometry(QtCore.QRect(215, 94, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditY.setFont(font)
        self.lineEditY.setObjectName(_fromUtf8("lineEditY"))
        self.lineEditW = QtGui.QLineEdit(self.groupBoxOptions)
        self.lineEditW.setEnabled(True)
        self.lineEditW.setGeometry(QtCore.QRect(275, 94, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditW.setFont(font)
        self.lineEditW.setObjectName(_fromUtf8("lineEditW"))
        self.lineEditH = QtGui.QLineEdit(self.groupBoxOptions)
        self.lineEditH.setEnabled(True)
        self.lineEditH.setGeometry(QtCore.QRect(335, 94, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditH.setFont(font)
        self.lineEditH.setObjectName(_fromUtf8("lineEditH"))
        self.checkBoxSF2 = QtGui.QCheckBox(self.groupBoxOptions)
        self.checkBoxSF2.setGeometry(QtCore.QRect(153, 33, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxSF2.setFont(font)
        self.checkBoxSF2.setObjectName(_fromUtf8("checkBoxSF2"))
        self.checkBoxSF3 = QtGui.QCheckBox(self.groupBoxOptions)
        self.checkBoxSF3.setGeometry(QtCore.QRect(203, 33, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxSF3.setFont(font)
        self.checkBoxSF3.setObjectName(_fromUtf8("checkBoxSF3"))
        self.checkBoxSF4 = QtGui.QCheckBox(self.groupBoxOptions)
        self.checkBoxSF4.setGeometry(QtCore.QRect(250, 33, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxSF4.setFont(font)
        self.checkBoxSF4.setObjectName(_fromUtf8("checkBoxSF4"))
        self.label = QtGui.QLabel(self.groupBoxOptions)
        self.label.setGeometry(QtCore.QRect(10, 172, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.checkBox = QtGui.QCheckBox(self.groupBoxOptions)
        self.checkBox.setGeometry(QtCore.QRect(155, 171, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.groupBoxOptions)
        self.checkBox_2.setGeometry(QtCore.QRect(245, 169, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.label_2 = QtGui.QLabel(self.groupBoxOptions)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.checkBoxRF = QtGui.QCheckBox(self.groupBoxOptions)
        self.checkBoxRF.setGeometry(QtCore.QRect(156, 200, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxRF.setFont(font)
        self.checkBoxRF.setObjectName(_fromUtf8("checkBoxRF"))
        self.pushButtonGetDimensions = QtGui.QPushButton(self.groupBoxOptions)
        self.pushButtonGetDimensions.setEnabled(True)
        self.pushButtonGetDimensions.setGeometry(QtCore.QRect(390, 90, 101, 27))
        self.pushButtonGetDimensions.setCheckable(False)
        self.pushButtonGetDimensions.setObjectName(_fromUtf8("pushButtonGetDimensions"))
        self.radioButtonAuto = QtGui.QRadioButton(self.groupBoxOptions)
        self.radioButtonAuto.setGeometry(QtCore.QRect(247, 60, 105, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        font.setItalic(False)
        self.radioButtonAuto.setFont(font)
        self.radioButtonAuto.setObjectName(_fromUtf8("radioButtonAuto"))
        self.radioButtonMan = QtGui.QRadioButton(self.groupBoxOptions)
        self.radioButtonMan.setGeometry(QtCore.QRect(153, 60, 105, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        font.setItalic(False)
        self.radioButtonMan.setFont(font)
        self.radioButtonMan.setChecked(True)
        self.radioButtonMan.setObjectName(_fromUtf8("radioButtonMan"))
        self.radioButtonNo = QtGui.QRadioButton(self.groupBoxOptions)
        self.radioButtonNo.setGeometry(QtCore.QRect(359, 60, 105, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        self.radioButtonNo.setFont(font)
        self.radioButtonNo.setObjectName(_fromUtf8("radioButtonNo"))
        self.label_zwait = QtGui.QLabel(self.groupBoxOptions)
        self.label_zwait.setGeometry(QtCore.QRect(337, 120, 151, 21))
        self.label_zwait.setText(_fromUtf8(""))
        self.label_zwait.setObjectName(_fromUtf8("label_zwait"))
        self.groupBoxuCTOnly = QtGui.QGroupBox(self.frame)
        self.groupBoxuCTOnly.setGeometry(QtCore.QRect(20, 350, 301, 221))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxuCTOnly.setFont(font)
        self.groupBoxuCTOnly.setStyleSheet(_fromUtf8("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;    \n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;   \n"
"}"))
        self.groupBoxuCTOnly.setFlat(False)
        self.groupBoxuCTOnly.setCheckable(True)
        self.groupBoxuCTOnly.setChecked(True)
        self.groupBoxuCTOnly.setObjectName(_fromUtf8("groupBoxuCTOnly"))
        self.formLayoutWidget_9 = QtGui.QWidget(self.groupBoxuCTOnly)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(10, 35, 261, 183))
        self.formLayoutWidget_9.setObjectName(_fromUtf8("formLayoutWidget_9"))
        self.formLayoutuCTOnly = QtGui.QFormLayout(self.formLayoutWidget_9)
        self.formLayoutuCTOnly.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayoutuCTOnly.setMargin(0)
        self.formLayoutuCTOnly.setObjectName(_fromUtf8("formLayoutuCTOnly"))
        self.pushButtonCTRecon = QtGui.QPushButton(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCTRecon.setFont(font)
        self.pushButtonCTRecon.setObjectName(_fromUtf8("pushButtonCTRecon"))
        self.formLayoutuCTOnly.setWidget(0, QtGui.QFormLayout.LabelRole, self.pushButtonCTRecon)
        self.lineEditCTRecon = QtGui.QLineEdit(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditCTRecon.setFont(font)
        self.lineEditCTRecon.setObjectName(_fromUtf8("lineEditCTRecon"))
        self.formLayoutuCTOnly.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditCTRecon)
        self.pushButtonCTSPR = QtGui.QPushButton(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCTSPR.setFont(font)
        self.pushButtonCTSPR.setObjectName(_fromUtf8("pushButtonCTSPR"))
        self.formLayoutuCTOnly.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButtonCTSPR)
        self.lineEditCTSPR = QtGui.QLineEdit(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditCTSPR.setFont(font)
        self.lineEditCTSPR.setObjectName(_fromUtf8("lineEditCTSPR"))
        self.formLayoutuCTOnly.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditCTSPR)
        self.pushButtonCTARC = QtGui.QPushButton(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCTARC.setFont(font)
        self.pushButtonCTARC.setObjectName(_fromUtf8("pushButtonCTARC"))
        self.formLayoutuCTOnly.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButtonCTARC)
        self.lineEditCTARC = QtGui.QLineEdit(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditCTARC.setFont(font)
        self.lineEditCTARC.setObjectName(_fromUtf8("lineEditCTARC"))
        self.formLayoutuCTOnly.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditCTARC)
        self.comboBoxCh = QtGui.QComboBox(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxCh.setFont(font)
        self.comboBoxCh.setObjectName(_fromUtf8("comboBoxCh"))
        self.comboBoxCh.addItem(_fromUtf8(""))
        self.formLayoutuCTOnly.setWidget(4, QtGui.QFormLayout.LabelRole, self.comboBoxCh)
        self.pushButtonScan = QtGui.QPushButton(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        self.pushButtonScan.setFont(font)
        self.pushButtonScan.setObjectName(_fromUtf8("pushButtonScan"))
        self.formLayoutuCTOnly.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButtonScan)
        self.lineEditScan = QtGui.QLineEdit(self.formLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        self.lineEditScan.setFont(font)
        self.lineEditScan.setObjectName(_fromUtf8("lineEditScan"))
        self.formLayoutuCTOnly.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditScan)
        self.groupBoxReconInfo = QtGui.QGroupBox(self.frame)
        self.groupBoxReconInfo.setGeometry(QtCore.QRect(20, 109, 711, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxReconInfo.setFont(font)
        self.groupBoxReconInfo.setAutoFillBackground(False)
        self.groupBoxReconInfo.setStyleSheet(_fromUtf8("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;    \n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;   \n"
"}"))
        self.groupBoxReconInfo.setFlat(False)
        self.groupBoxReconInfo.setCheckable(False)
        self.groupBoxReconInfo.setObjectName(_fromUtf8("groupBoxReconInfo"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.groupBoxReconInfo)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 33, 691, 31))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayoutReconInfo = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayoutReconInfo.setMargin(0)
        self.gridLayoutReconInfo.setObjectName(_fromUtf8("gridLayoutReconInfo"))
        self.lcdNumberFile = QtGui.QLCDNumber(self.gridLayoutWidget_4)
        self.lcdNumberFile.setSmallDecimalPoint(True)
        self.lcdNumberFile.setNumDigits(7)
        self.lcdNumberFile.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberFile.setObjectName(_fromUtf8("lcdNumberFile"))
        self.gridLayoutReconInfo.addWidget(self.lcdNumberFile, 0, 1, 1, 1)
        self.lcdNumberPixel = QtGui.QLCDNumber(self.gridLayoutWidget_4)
        self.lcdNumberPixel.setSmallDecimalPoint(True)
        self.lcdNumberPixel.setNumDigits(7)
        self.lcdNumberPixel.setProperty("value", 0.0)
        self.lcdNumberPixel.setObjectName(_fromUtf8("lcdNumberPixel"))
        self.gridLayoutReconInfo.addWidget(self.lcdNumberPixel, 0, 3, 1, 1)
        self.labelFile = QtGui.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelFile.setFont(font)
        self.labelFile.setObjectName(_fromUtf8("labelFile"))
        self.gridLayoutReconInfo.addWidget(self.labelFile, 0, 0, 1, 1)
        self.labelPixel = QtGui.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPixel.setFont(font)
        self.labelPixel.setObjectName(_fromUtf8("labelPixel"))
        self.gridLayoutReconInfo.addWidget(self.labelPixel, 0, 2, 1, 1)
        self.pushButtonGo = QtGui.QPushButton(self.frame)
        self.pushButtonGo.setGeometry(QtCore.QRect(460, 860, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonGo.setFont(font)
        self.pushButtonGo.setDefault(False)
        self.pushButtonGo.setObjectName(_fromUtf8("pushButtonGo"))
        self.groupBoxModality_2 = QtGui.QGroupBox(self.frame)
        self.groupBoxModality_2.setGeometry(QtCore.QRect(740, 350, 501, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxModality_2.setFont(font)
        self.groupBoxModality_2.setStyleSheet(_fromUtf8("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;    \n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;   \n"
"}"))
        self.groupBoxModality_2.setObjectName(_fromUtf8("groupBoxModality_2"))
        self.textEditStatusMessages = QtGui.QTextEdit(self.groupBoxModality_2)
        self.textEditStatusMessages.setGeometry(QtCore.QRect(30, 30, 461, 71))
        self.textEditStatusMessages.setObjectName(_fromUtf8("textEditStatusMessages"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1274, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionChange_ID = QtGui.QAction(MainWindow)
        self.actionChange_ID.setObjectName(_fromUtf8("actionChange_ID"))
        self.actionManually_select_output_folder = QtGui.QAction(MainWindow)
        self.actionManually_select_output_folder.setObjectName(_fromUtf8("actionManually_select_output_folder"))
        self.actionAccurate_folder_size_calculation = QtGui.QAction(MainWindow)
        self.actionAccurate_folder_size_calculation.setObjectName(_fromUtf8("actionAccurate_folder_size_calculation"))
        self.menuOptions.addAction(self.actionChange_ID)
        self.menuOptions.addAction(self.actionManually_select_output_folder)
        self.menuOptions.addAction(self.actionAccurate_folder_size_calculation)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SIaH: Image Processor", None))
        self.pushButtonInput.setText(_translate("MainWindow", "Input folder", None))
        self.pushButtonOutput.setText(_translate("MainWindow", "Output folder", None))
        self.groupBoxOPTOnly.setTitle(_translate("MainWindow", "OPT only", None))
        self.checkBox_4.setText(_translate("MainWindow", "Channel 1", None))
        self.pushButton_9.setText(_translate("MainWindow", "Pick recon log", None))
        self.pushButton_10.setText(_translate("MainWindow", "Pick viewEND", None))
        self.pushButton_11.setText(_translate("MainWindow", "Pick SPR", None))
        self.pushButton_12.setText(_translate("MainWindow", "Pick ARC", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Ch-MPH", None))
        self.checkBox_5.setText(_translate("MainWindow", "Channel 2", None))
        self.pushButton_13.setText(_translate("MainWindow", "Pick recon log", None))
        self.pushButton_14.setText(_translate("MainWindow", "Pick viewEND", None))
        self.pushButton_15.setText(_translate("MainWindow", "Pick SPR", None))
        self.pushButton_16.setText(_translate("MainWindow", "Pick ARC", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Ch-MPH", None))
        self.checkBox_6.setText(_translate("MainWindow", "Channel 3", None))
        self.pushButton_17.setText(_translate("MainWindow", "Pick recon log", None))
        self.pushButton_18.setText(_translate("MainWindow", "Pick viewEND", None))
        self.pushButton_19.setText(_translate("MainWindow", "Pick SPR", None))
        self.pushButton_20.setText(_translate("MainWindow", "Pick ARC", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Ch-MPH", None))
        self.checkBox_7.setText(_translate("MainWindow", "Channel 4", None))
        self.pushButton_21.setText(_translate("MainWindow", "Pick recon log", None))
        self.pushButton_22.setText(_translate("MainWindow", "Pick viewEND", None))
        self.pushButton_23.setText(_translate("MainWindow", "Pick SPR", None))
        self.pushButton_24.setText(_translate("MainWindow", "Pick ARC", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Ch-MPH", None))
        self.groupBoxModality.setTitle(_translate("MainWindow", "Imaging modality", None))
        self.radioButtonuCT.setText(_translate("MainWindow", "µCT", None))
        self.radioButtonOPT.setText(_translate("MainWindow", "OPT", None))
        self.groupBoxID.setTitle(_translate("MainWindow", "Identification", None))
        self.labelAge.setText(_translate("MainWindow", "Stage", None))
        self.labelDate.setText(_translate("MainWindow", "Date", None))
        self.labelGroup.setText(_translate("MainWindow", "Gene", None))
        self.labelName.setText(_translate("MainWindow", "Full name", None))
        self.labelLitter.setText(_translate("MainWindow", "Litter", None))
        self.labelSex.setText(_translate("MainWindow", "Sex", None))
        self.labelZygosity.setText(_translate("MainWindow", "Zygosity", None))
        self.groupBoxOptions.setTitle(_translate("MainWindow", "Options", None))
        self.label_5.setText(_translate("MainWindow", "Downsize", None))
        self.label_13.setText(_translate("MainWindow", "Create movie", None))
        self.checkBoxMovie_2.setText(_translate("MainWindow", "Yes", None))
        self.label_14.setText(_translate("MainWindow", "Cropping", None))
        self.lineEditX.setText(_translate("MainWindow", "x", None))
        self.lineEditY.setText(_translate("MainWindow", "y", None))
        self.lineEditW.setText(_translate("MainWindow", "w", None))
        self.lineEditH.setText(_translate("MainWindow", "h", None))
        self.checkBoxSF2.setText(_translate("MainWindow", "2", None))
        self.checkBoxSF3.setText(_translate("MainWindow", "3", None))
        self.checkBoxSF4.setText(_translate("MainWindow", "4", None))
        self.label.setText(_translate("MainWindow", "Compress files", None))
        self.checkBox.setText(_translate("MainWindow", "Scans", None))
        self.checkBox_2.setText(_translate("MainWindow", "Original recons", None))
        self.label_2.setText(_translate("MainWindow", "Replace files", None))
        self.checkBoxRF.setText(_translate("MainWindow", "Yes", None))
        self.pushButtonGetDimensions.setText(_translate("MainWindow", "Get dimensions", None))
        self.radioButtonAuto.setText(_translate("MainWindow", "Automatic", None))
        self.radioButtonMan.setText(_translate("MainWindow", "Manual", None))
        self.radioButtonNo.setText(_translate("MainWindow", "No crop", None))
        self.groupBoxuCTOnly.setTitle(_translate("MainWindow", "µCT only", None))
        self.pushButtonCTRecon.setText(_translate("MainWindow", "Pick recon log", None))
        self.pushButtonCTSPR.setText(_translate("MainWindow", "Pick SPR", None))
        self.pushButtonCTARC.setText(_translate("MainWindow", "Pick ARC", None))
        self.comboBoxCh.setItemText(0, _translate("MainWindow", "Ch-X", None))
        self.pushButtonScan.setText(_translate("MainWindow", "Scan folder", None))
        self.groupBoxReconInfo.setTitle(_translate("MainWindow", "Recon File Info", None))
        self.labelFile.setText(_translate("MainWindow", "Folder size (Mb)", None))
        self.labelPixel.setText(_translate("MainWindow", "Pixel size (µm)", None))
        self.pushButtonGo.setText(_translate("MainWindow", "Go!", None))
        self.groupBoxModality_2.setTitle(_translate("MainWindow", "Status", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Adv. Options", None))
        self.actionChange_ID.setText(_translate("MainWindow", "Allow identification to be changed", None))
        self.actionManually_select_output_folder.setText(_translate("MainWindow", "Allow manually selection of output folder", None))
        self.actionAccurate_folder_size_calculation.setText(_translate("MainWindow", "Accurate folder size calculation", None))

