# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Tue Apr  8 17:51:58 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1260, 1039)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_10 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1241, 951))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1239, 949))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBoxOPTOnly = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxOPTOnly.setFont(font)
        self.groupBoxOPTOnly.setStyleSheet(_fromUtf8("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;\n"
"    background:url(:/assets/subWindowBackground);\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;\n"
"}"))
        self.groupBoxOPTOnly.setCheckable(True)
        self.groupBoxOPTOnly.setChecked(False)
        self.groupBoxOPTOnly.setObjectName(_fromUtf8("groupBoxOPTOnly"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBoxOPTOnly)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.checkBox_7 = QtGui.QCheckBox(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox_7)
        self.lineEdit_30 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_30.setFont(font)
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_30)
        self.pushButton_21 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButton_21)
        self.lineEdit_31 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_31.setFont(font)
        self.lineEdit_31.setObjectName(_fromUtf8("lineEdit_31"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_31)
        self.pushButton_22 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_22)
        self.lineEdit_32 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_32.setFont(font)
        self.lineEdit_32.setObjectName(_fromUtf8("lineEdit_32"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_32)
        self.pushButton_23 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButton_23)
        self.lineEdit_33 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_33.setFont(font)
        self.lineEdit_33.setObjectName(_fromUtf8("lineEdit_33"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_33)
        self.pushButton_24 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButton_24)
        self.lineEdit_34 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_34.setFont(font)
        self.lineEdit_34.setObjectName(_fromUtf8("lineEdit_34"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_34)
        self.comboBox_6 = QtGui.QComboBox(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.LabelRole, self.comboBox_6)
        self.gridLayout_7.addLayout(self.formLayout_6, 1, 3, 1, 1)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.checkBox_6 = QtGui.QCheckBox(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox_6)
        self.lineEdit_25 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_25)
        self.pushButton_17 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButton_17)
        self.lineEdit_26 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_26)
        self.pushButton_18 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_18)
        self.lineEdit_27 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_27.setFont(font)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_27)
        self.pushButton_19 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButton_19)
        self.lineEdit_28 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_28)
        self.pushButton_20 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButton_20)
        self.lineEdit_29 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_29.setFont(font)
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_29)
        self.comboBox_5 = QtGui.QComboBox(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.LabelRole, self.comboBox_5)
        self.gridLayout_7.addLayout(self.formLayout_5, 1, 2, 1, 1)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.checkBox_5 = QtGui.QCheckBox(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox_5)
        self.lineEdit_20 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_20)
        self.pushButton_13 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButton_13)
        self.lineEdit_21 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_21)
        self.pushButton_14 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_14)
        self.lineEdit_22 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_22)
        self.pushButton_15 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButton_15)
        self.lineEdit_23 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_23)
        self.pushButton_16 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButton_16)
        self.lineEdit_24 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_24)
        self.comboBox_4 = QtGui.QComboBox(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.comboBox_4)
        self.gridLayout_7.addLayout(self.formLayout_4, 1, 1, 1, 1)
        self.formLayoutCh1 = QtGui.QFormLayout()
        self.formLayoutCh1.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayoutCh1.setObjectName(_fromUtf8("formLayoutCh1"))
        self.checkBox_4 = QtGui.QCheckBox(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.formLayoutCh1.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox_4)
        self.lineEdit_15 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.formLayoutCh1.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_15)
        self.pushButton_9 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.formLayoutCh1.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButton_9)
        self.lineEdit_16 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.formLayoutCh1.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_16)
        self.pushButton_10 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.formLayoutCh1.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_10)
        self.lineEdit_17 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.formLayoutCh1.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_17)
        self.pushButton_11 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.formLayoutCh1.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButton_11)
        self.lineEdit_18 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.formLayoutCh1.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_18)
        self.pushButton_12 = QtGui.QPushButton(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.formLayoutCh1.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButton_12)
        self.lineEdit_19 = QtGui.QLineEdit(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.formLayoutCh1.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_19)
        self.comboBox_3 = QtGui.QComboBox(self.groupBoxOPTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.formLayoutCh1.setWidget(5, QtGui.QFormLayout.LabelRole, self.comboBox_3)
        self.gridLayout_7.addLayout(self.formLayoutCh1, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxOPTOnly, 7, 0, 1, 2)
        self.groupBoxModality = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxModality.setFont(font)
        self.groupBoxModality.setStyleSheet(_fromUtf8("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;\n"
"}"))
        self.groupBoxModality.setObjectName(_fromUtf8("groupBoxModality"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxModality)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radioButtonuCT = QtGui.QRadioButton(self.groupBoxModality)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonuCT.setFont(font)
        self.radioButtonuCT.setChecked(True)
        self.radioButtonuCT.setObjectName(_fromUtf8("radioButtonuCT"))
        self.gridLayout_3.addWidget(self.radioButtonuCT, 1, 0, 1, 1)
        self.radioButtonOPT = QtGui.QRadioButton(self.groupBoxModality)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonOPT.setFont(font)
        self.radioButtonOPT.setObjectName(_fromUtf8("radioButtonOPT"))
        self.gridLayout_3.addWidget(self.radioButtonOPT, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxModality, 0, 1, 1, 1)
        self.groupBoxOptions = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxOptions.setMaximumSize(QtCore.QSize(570, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxOptions.setFont(font)
        self.groupBoxOptions.setStyleSheet(_fromUtf8("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;\n"
"}"))
        self.groupBoxOptions.setObjectName(_fromUtf8("groupBoxOptions"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxOptions)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.checkBoxPixel = QtGui.QCheckBox(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxPixel.setFont(font)
        self.checkBoxPixel.setChecked(False)
        self.checkBoxPixel.setObjectName(_fromUtf8("checkBoxPixel"))
        self.gridLayout_4.addWidget(self.checkBoxPixel, 0, 3, 1, 1)
        self.lineEditX = QtGui.QLineEdit(self.groupBoxOptions)
        self.lineEditX.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditX.setFont(font)
        self.lineEditX.setReadOnly(False)
        self.lineEditX.setObjectName(_fromUtf8("lineEditX"))
        self.gridLayout_4.addWidget(self.lineEditX, 2, 1, 1, 1)
        self.lineEditPixel = QtGui.QLineEdit(self.groupBoxOptions)
        self.lineEditPixel.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditPixel.setFont(font)
        self.lineEditPixel.setObjectName(_fromUtf8("lineEditPixel"))
        self.gridLayout_4.addWidget(self.lineEditPixel, 0, 4, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBoxOptions)
        self.label_13.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBoxOptions)
        self.label.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 4, 0, 1, 1)
        self.checkBoxMovie_2 = QtGui.QCheckBox(self.groupBoxOptions)
        self.checkBoxMovie_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxMovie_2.setFont(font)
        self.checkBoxMovie_2.setObjectName(_fromUtf8("checkBoxMovie_2"))
        self.gridLayout_4.addWidget(self.checkBoxMovie_2, 3, 1, 1, 1)
        self.radioButtonNo = QtGui.QRadioButton(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        self.radioButtonNo.setFont(font)
        self.radioButtonNo.setObjectName(_fromUtf8("radioButtonNo"))
        self.gridLayout_4.addWidget(self.radioButtonNo, 1, 3, 1, 1)
        self.radioButtonAuto = QtGui.QRadioButton(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        font.setItalic(False)
        self.radioButtonAuto.setFont(font)
        self.radioButtonAuto.setObjectName(_fromUtf8("radioButtonAuto"))
        self.gridLayout_4.addWidget(self.radioButtonAuto, 1, 2, 1, 1)
        self.radioButtonMan = QtGui.QRadioButton(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        font.setItalic(False)
        self.radioButtonMan.setFont(font)
        self.radioButtonMan.setChecked(True)
        self.radioButtonMan.setObjectName(_fromUtf8("radioButtonMan"))
        self.gridLayout_4.addWidget(self.radioButtonMan, 1, 1, 1, 1)
        self.checkBoxRF = QtGui.QCheckBox(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxRF.setFont(font)
        self.checkBoxRF.setObjectName(_fromUtf8("checkBoxRF"))
        self.gridLayout_4.addWidget(self.checkBoxRF, 5, 1, 1, 1)
        self.checkBoxCropComp = QtGui.QCheckBox(self.groupBoxOptions)
        self.checkBoxCropComp.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxCropComp.setFont(font)
        self.checkBoxCropComp.setObjectName(_fromUtf8("checkBoxCropComp"))
        self.gridLayout_4.addWidget(self.checkBoxCropComp, 4, 3, 1, 1)
        self.checkBoxScansReconComp = QtGui.QCheckBox(self.groupBoxOptions)
        self.checkBoxScansReconComp.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxScansReconComp.setFont(font)
        self.checkBoxScansReconComp.setObjectName(_fromUtf8("checkBoxScansReconComp"))
        self.gridLayout_4.addWidget(self.checkBoxScansReconComp, 4, 1, 1, 2)
        self.pushButtonGetDimensions = QtGui.QPushButton(self.groupBoxOptions)
        self.pushButtonGetDimensions.setEnabled(True)
        self.pushButtonGetDimensions.setCheckable(False)
        self.pushButtonGetDimensions.setObjectName(_fromUtf8("pushButtonGetDimensions"))
        self.gridLayout_4.addWidget(self.pushButtonGetDimensions, 1, 4, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBoxSF2 = QtGui.QCheckBox(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxSF2.setFont(font)
        self.checkBoxSF2.setChecked(True)
        self.checkBoxSF2.setObjectName(_fromUtf8("checkBoxSF2"))
        self.horizontalLayout_3.addWidget(self.checkBoxSF2)
        self.checkBoxSF3 = QtGui.QCheckBox(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxSF3.setFont(font)
        self.checkBoxSF3.setChecked(True)
        self.checkBoxSF3.setObjectName(_fromUtf8("checkBoxSF3"))
        self.horizontalLayout_3.addWidget(self.checkBoxSF3)
        self.checkBoxSF4 = QtGui.QCheckBox(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxSF4.setFont(font)
        self.checkBoxSF4.setChecked(True)
        self.checkBoxSF4.setObjectName(_fromUtf8("checkBoxSF4"))
        self.horizontalLayout_3.addWidget(self.checkBoxSF4)
        self.checkBoxSF5 = QtGui.QCheckBox(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxSF5.setFont(font)
        self.checkBoxSF5.setChecked(True)
        self.checkBoxSF5.setObjectName(_fromUtf8("checkBoxSF5"))
        self.horizontalLayout_3.addWidget(self.checkBoxSF5)
        self.checkBoxSF6 = QtGui.QCheckBox(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxSF6.setFont(font)
        self.checkBoxSF6.setChecked(True)
        self.checkBoxSF6.setObjectName(_fromUtf8("checkBoxSF6"))
        self.horizontalLayout_3.addWidget(self.checkBoxSF6)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 1, 1, 2)
        self.lineEditH = QtGui.QLineEdit(self.groupBoxOptions)
        self.lineEditH.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditH.setFont(font)
        self.lineEditH.setObjectName(_fromUtf8("lineEditH"))
        self.gridLayout_4.addWidget(self.lineEditH, 2, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 5, 0, 1, 1)
        self.lineEditW = QtGui.QLineEdit(self.groupBoxOptions)
        self.lineEditW.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditW.setFont(font)
        self.lineEditW.setObjectName(_fromUtf8("lineEditW"))
        self.gridLayout_4.addWidget(self.lineEditW, 2, 3, 1, 1)
        self.lineEditY = QtGui.QLineEdit(self.groupBoxOptions)
        self.lineEditY.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditY.setFont(font)
        self.lineEditY.setObjectName(_fromUtf8("lineEditY"))
        self.gridLayout_4.addWidget(self.lineEditY, 2, 2, 1, 1)
        self.label_zwait = QtGui.QLabel(self.groupBoxOptions)
        self.label_zwait.setText(_fromUtf8(""))
        self.label_zwait.setObjectName(_fromUtf8("label_zwait"))
        self.gridLayout_4.addWidget(self.label_zwait, 3, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 1, 0, 2, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxOptions, 1, 1, 2, 1)
        self.groupBoxID = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxID.setMinimumSize(QtCore.QSize(600, 120))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxID.setFont(font)
        self.groupBoxID.setStyleSheet(_fromUtf8("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;\n"
"}"))
        self.groupBoxID.setObjectName(_fromUtf8("groupBoxID"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBoxID)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayoutName = QtGui.QGridLayout()
        self.gridLayoutName.setObjectName(_fromUtf8("gridLayoutName"))
        self.labelName = QtGui.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelName.setFont(font)
        self.labelName.setObjectName(_fromUtf8("labelName"))
        self.gridLayoutName.addWidget(self.labelName, 0, 0, 1, 1)
        self.lineEditName = QtGui.QLineEdit(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditName.setFont(font)
        self.lineEditName.setReadOnly(False)
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.gridLayoutName.addWidget(self.lineEditName, 0, 1, 1, 1)
        self.pushButtonUpdate = QtGui.QPushButton(self.groupBoxID)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        self.pushButtonUpdate.setFont(font)
        self.pushButtonUpdate.setObjectName(_fromUtf8("pushButtonUpdate"))
        self.gridLayoutName.addWidget(self.pushButtonUpdate, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayoutName, 3, 0, 1, 1)
        self.gridLayoutIDs = QtGui.QGridLayout()
        self.gridLayoutIDs.setObjectName(_fromUtf8("gridLayoutIDs"))
        self.labelAge = QtGui.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelAge.setFont(font)
        self.labelAge.setObjectName(_fromUtf8("labelAge"))
        self.gridLayoutIDs.addWidget(self.labelAge, 0, 4, 1, 1)
        self.lineEditGroup = QtGui.QLineEdit(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditGroup.setFont(font)
        self.lineEditGroup.setReadOnly(True)
        self.lineEditGroup.setObjectName(_fromUtf8("lineEditGroup"))
        self.gridLayoutIDs.addWidget(self.lineEditGroup, 0, 3, 1, 1)
        self.lineEditDate = QtGui.QLineEdit(self.groupBoxID)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditDate.sizePolicy().hasHeightForWidth())
        self.lineEditDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditDate.setFont(font)
        self.lineEditDate.setText(_fromUtf8(""))
        self.lineEditDate.setReadOnly(True)
        self.lineEditDate.setObjectName(_fromUtf8("lineEditDate"))
        self.gridLayoutIDs.addWidget(self.lineEditDate, 0, 1, 1, 1)
        self.lineEditAge = QtGui.QLineEdit(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditAge.setFont(font)
        self.lineEditAge.setReadOnly(True)
        self.lineEditAge.setObjectName(_fromUtf8("lineEditAge"))
        self.gridLayoutIDs.addWidget(self.lineEditAge, 0, 5, 1, 1)
        self.labelDate = QtGui.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelDate.setFont(font)
        self.labelDate.setObjectName(_fromUtf8("labelDate"))
        self.gridLayoutIDs.addWidget(self.labelDate, 0, 0, 1, 1)
        self.labelGroup = QtGui.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelGroup.setFont(font)
        self.labelGroup.setObjectName(_fromUtf8("labelGroup"))
        self.gridLayoutIDs.addWidget(self.labelGroup, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayoutIDs, 1, 0, 1, 1)
        self.gridLayoutIDs_2 = QtGui.QGridLayout()
        self.gridLayoutIDs_2.setObjectName(_fromUtf8("gridLayoutIDs_2"))
        self.labelLitter = QtGui.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelLitter.setFont(font)
        self.labelLitter.setObjectName(_fromUtf8("labelLitter"))
        self.gridLayoutIDs_2.addWidget(self.labelLitter, 0, 0, 1, 1)
        self.lineEditLitter = QtGui.QLineEdit(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditLitter.setFont(font)
        self.lineEditLitter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditLitter.setText(_fromUtf8(""))
        self.lineEditLitter.setReadOnly(True)
        self.lineEditLitter.setObjectName(_fromUtf8("lineEditLitter"))
        self.gridLayoutIDs_2.addWidget(self.lineEditLitter, 0, 1, 1, 1)
        self.labelSex = QtGui.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelSex.setFont(font)
        self.labelSex.setObjectName(_fromUtf8("labelSex"))
        self.gridLayoutIDs_2.addWidget(self.labelSex, 0, 4, 1, 1)
        self.lineEditSex = QtGui.QLineEdit(self.groupBoxID)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        self.lineEditSex.setFont(font)
        self.lineEditSex.setReadOnly(True)
        self.lineEditSex.setObjectName(_fromUtf8("lineEditSex"))
        self.gridLayoutIDs_2.addWidget(self.lineEditSex, 0, 5, 1, 1)
        self.lineEditZygosity = QtGui.QLineEdit(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditZygosity.setFont(font)
        self.lineEditZygosity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditZygosity.setReadOnly(True)
        self.lineEditZygosity.setObjectName(_fromUtf8("lineEditZygosity"))
        self.gridLayoutIDs_2.addWidget(self.lineEditZygosity, 0, 3, 1, 1)
        self.labelZygosity = QtGui.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelZygosity.setFont(font)
        self.labelZygosity.setObjectName(_fromUtf8("labelZygosity"))
        self.gridLayoutIDs_2.addWidget(self.labelZygosity, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayoutIDs_2, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(10)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 4, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxID, 2, 0, 2, 1)
        self.groupBoxModality_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxModality_2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxModality_2.setFont(font)
        self.groupBoxModality_2.setStyleSheet(_fromUtf8("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;\n"
"}"))
        self.groupBoxModality_2.setObjectName(_fromUtf8("groupBoxModality_2"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBoxModality_2)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        spacerItem4 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem4, 0, 0, 1, 1)
        self.textEditStatusMessages = QtGui.QTextEdit(self.groupBoxModality_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textEditStatusMessages.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(14)
        self.textEditStatusMessages.setFont(font)
        self.textEditStatusMessages.setObjectName(_fromUtf8("textEditStatusMessages"))
        self.gridLayout_12.addWidget(self.textEditStatusMessages, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxModality_2, 3, 1, 1, 1)
        self.groupBoxReconInfo = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxReconInfo.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxReconInfo.setFont(font)
        self.groupBoxReconInfo.setAutoFillBackground(False)
        self.groupBoxReconInfo.setStyleSheet(_fromUtf8("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;\n"
"}"))
        self.groupBoxReconInfo.setFlat(False)
        self.groupBoxReconInfo.setCheckable(False)
        self.groupBoxReconInfo.setObjectName(_fromUtf8("groupBoxReconInfo"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBoxReconInfo)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayoutReconInfo = QtGui.QGridLayout()
        self.gridLayoutReconInfo.setObjectName(_fromUtf8("gridLayoutReconInfo"))
        self.labelPixel = QtGui.QLabel(self.groupBoxReconInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPixel.setFont(font)
        self.labelPixel.setObjectName(_fromUtf8("labelPixel"))
        self.gridLayoutReconInfo.addWidget(self.labelPixel, 0, 2, 1, 1)
        self.lcdNumberPixel = QtGui.QLCDNumber(self.groupBoxReconInfo)
        self.lcdNumberPixel.setSmallDecimalPoint(True)
        self.lcdNumberPixel.setNumDigits(7)
        self.lcdNumberPixel.setProperty("value", 0.0)
        self.lcdNumberPixel.setObjectName(_fromUtf8("lcdNumberPixel"))
        self.gridLayoutReconInfo.addWidget(self.lcdNumberPixel, 0, 3, 1, 1)
        self.lcdNumberFile = QtGui.QLCDNumber(self.groupBoxReconInfo)
        self.lcdNumberFile.setSmallDecimalPoint(True)
        self.lcdNumberFile.setNumDigits(7)
        self.lcdNumberFile.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumberFile.setObjectName(_fromUtf8("lcdNumberFile"))
        self.gridLayoutReconInfo.addWidget(self.lcdNumberFile, 0, 1, 1, 1)
        self.labelFile = QtGui.QLabel(self.groupBoxReconInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelFile.setFont(font)
        self.labelFile.setObjectName(_fromUtf8("labelFile"))
        self.gridLayoutReconInfo.addWidget(self.labelFile, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayoutReconInfo, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem5, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxReconInfo, 1, 0, 1, 1)
        self.groupBoxuCTOnly = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxuCTOnly.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxuCTOnly.setFont(font)
        self.groupBoxuCTOnly.setStyleSheet(_fromUtf8("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;\n"
"}"))
        self.groupBoxuCTOnly.setFlat(False)
        self.groupBoxuCTOnly.setCheckable(True)
        self.groupBoxuCTOnly.setChecked(True)
        self.groupBoxuCTOnly.setObjectName(_fromUtf8("groupBoxuCTOnly"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBoxuCTOnly)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem6 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem6, 0, 0, 1, 1)
        self.formLayoutuCTOnly = QtGui.QFormLayout()
        self.formLayoutuCTOnly.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayoutuCTOnly.setObjectName(_fromUtf8("formLayoutuCTOnly"))
        self.pushButtonCTRecon = QtGui.QPushButton(self.groupBoxuCTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCTRecon.setFont(font)
        self.pushButtonCTRecon.setObjectName(_fromUtf8("pushButtonCTRecon"))
        self.formLayoutuCTOnly.setWidget(0, QtGui.QFormLayout.LabelRole, self.pushButtonCTRecon)
        self.lineEditCTRecon = QtGui.QLineEdit(self.groupBoxuCTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditCTRecon.setFont(font)
        self.lineEditCTRecon.setObjectName(_fromUtf8("lineEditCTRecon"))
        self.formLayoutuCTOnly.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditCTRecon)
        self.pushButtonCTSPR = QtGui.QPushButton(self.groupBoxuCTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCTSPR.setFont(font)
        self.pushButtonCTSPR.setObjectName(_fromUtf8("pushButtonCTSPR"))
        self.formLayoutuCTOnly.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButtonCTSPR)
        self.lineEditCTSPR = QtGui.QLineEdit(self.groupBoxuCTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditCTSPR.setFont(font)
        self.lineEditCTSPR.setObjectName(_fromUtf8("lineEditCTSPR"))
        self.formLayoutuCTOnly.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditCTSPR)
        self.pushButtonCTARC = QtGui.QPushButton(self.groupBoxuCTOnly)
        self.pushButtonCTARC.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCTARC.setFont(font)
        self.pushButtonCTARC.setObjectName(_fromUtf8("pushButtonCTARC"))
        self.formLayoutuCTOnly.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButtonCTARC)
        self.lineEditCTARC = QtGui.QLineEdit(self.groupBoxuCTOnly)
        self.lineEditCTARC.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditCTARC.setFont(font)
        self.lineEditCTARC.setObjectName(_fromUtf8("lineEditCTARC"))
        self.formLayoutuCTOnly.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditCTARC)
        self.comboBoxCh = QtGui.QComboBox(self.groupBoxuCTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxCh.setFont(font)
        self.comboBoxCh.setObjectName(_fromUtf8("comboBoxCh"))
        self.comboBoxCh.addItem(_fromUtf8(""))
        self.formLayoutuCTOnly.setWidget(4, QtGui.QFormLayout.LabelRole, self.comboBoxCh)
        self.pushButtonScan = QtGui.QPushButton(self.groupBoxuCTOnly)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        self.pushButtonScan.setFont(font)
        self.pushButtonScan.setObjectName(_fromUtf8("pushButtonScan"))
        self.formLayoutuCTOnly.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButtonScan)
        self.lineEditScan = QtGui.QLineEdit(self.groupBoxuCTOnly)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(12)
        self.lineEditScan.setFont(font)
        self.lineEditScan.setObjectName(_fromUtf8("lineEditScan"))
        self.formLayoutuCTOnly.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditScan)
        self.gridLayout_8.addLayout(self.formLayoutuCTOnly, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxuCTOnly, 6, 0, 1, 1)
        self.gridLayoutFileSelect = QtGui.QGridLayout()
        self.gridLayoutFileSelect.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayoutFileSelect.setObjectName(_fromUtf8("gridLayoutFileSelect"))
        self.pushButtonOutput = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonOutput.setFont(font)
        self.pushButtonOutput.setObjectName(_fromUtf8("pushButtonOutput"))
        self.gridLayoutFileSelect.addWidget(self.pushButtonOutput, 1, 0, 1, 1)
        self.lineEditInput = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditInput.setFont(font)
        self.lineEditInput.setObjectName(_fromUtf8("lineEditInput"))
        self.gridLayoutFileSelect.addWidget(self.lineEditInput, 0, 1, 1, 1)
        self.lineEditOutput = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditOutput.setFont(font)
        self.lineEditOutput.setObjectName(_fromUtf8("lineEditOutput"))
        self.gridLayoutFileSelect.addWidget(self.lineEditOutput, 1, 1, 1, 1)
        self.pushButtonInput = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonInput.setFont(font)
        self.pushButtonInput.setObjectName(_fromUtf8("pushButtonInput"))
        self.gridLayoutFileSelect.addWidget(self.pushButtonInput, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayoutFileSelect, 0, 0, 1, 1)
        self.pushButtonGo = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButtonGo.setMinimumSize(QtCore.QSize(0, 65))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonGo.setFont(font)
        self.pushButtonGo.setDefault(False)
        self.pushButtonGo.setObjectName(_fromUtf8("pushButtonGo"))
        self.gridLayout_2.addWidget(self.pushButtonGo, 8, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1216, 895))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tableWidget = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_9.addWidget(self.scrollArea_2, 7, 0, 1, 3)
        self.pushButtonStart = QtGui.QPushButton(self.tab_2)
        self.pushButtonStart.setObjectName(_fromUtf8("pushButtonStart"))
        self.gridLayout_9.addWidget(self.pushButtonStart, 6, 0, 1, 1)
        self.pushButtonStop = QtGui.QPushButton(self.tab_2)
        self.pushButtonStop.setEnabled(False)
        self.pushButtonStop.setObjectName(_fromUtf8("pushButtonStop"))
        self.gridLayout_9.addWidget(self.pushButtonStop, 6, 1, 1, 1)
        self.pushButtonAdd = QtGui.QPushButton(self.tab_2)
        self.pushButtonAdd.setObjectName(_fromUtf8("pushButtonAdd"))
        self.gridLayout_9.addWidget(self.pushButtonAdd, 6, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1260, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMore_Options = QtGui.QMenu(self.menubar)
        self.menuMore_Options.setObjectName(_fromUtf8("menuMore_Options"))
        MainWindow.setMenuBar(self.menubar)
        self.actionChange_ID = QtGui.QAction(MainWindow)
        self.actionChange_ID.setObjectName(_fromUtf8("actionChange_ID"))
        self.actionManually_select_output_folder = QtGui.QAction(MainWindow)
        self.actionManually_select_output_folder.setObjectName(_fromUtf8("actionManually_select_output_folder"))
        self.actionAccurate_folder_size_calculation = QtGui.QAction(MainWindow)
        self.actionAccurate_folder_size_calculation.setObjectName(_fromUtf8("actionAccurate_folder_size_calculation"))
        self.actionResize = QtGui.QAction(MainWindow)
        self.actionResize.setObjectName(_fromUtf8("actionResize"))
        self.actionReset_screen_size = QtGui.QAction(MainWindow)
        self.actionReset_screen_size.setObjectName(_fromUtf8("actionReset_screen_size"))
        self.menuMore_Options.addAction(self.actionResize)
        self.menuMore_Options.addAction(self.actionReset_screen_size)
        self.menubar.addAction(self.menuMore_Options.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "HARP", None))
        self.groupBoxOPTOnly.setTitle(_translate("MainWindow", "OPT only", None))
        self.checkBox_7.setText(_translate("MainWindow", "Channel 4", None))
        self.pushButton_21.setText(_translate("MainWindow", "Pick recon log", None))
        self.pushButton_22.setText(_translate("MainWindow", "Pick viewEND", None))
        self.pushButton_23.setText(_translate("MainWindow", "Pick SPR", None))
        self.pushButton_24.setText(_translate("MainWindow", "Pick ARC", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Ch-MPH", None))
        self.checkBox_6.setText(_translate("MainWindow", "Channel 3", None))
        self.pushButton_17.setText(_translate("MainWindow", "Pick recon log", None))
        self.pushButton_18.setText(_translate("MainWindow", "Pick viewEND", None))
        self.pushButton_19.setText(_translate("MainWindow", "Pick SPR", None))
        self.pushButton_20.setText(_translate("MainWindow", "Pick ARC", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Ch-MPH", None))
        self.checkBox_5.setText(_translate("MainWindow", "Channel 2", None))
        self.pushButton_13.setText(_translate("MainWindow", "Pick recon log", None))
        self.pushButton_14.setText(_translate("MainWindow", "Pick viewEND", None))
        self.pushButton_15.setText(_translate("MainWindow", "Pick SPR", None))
        self.pushButton_16.setText(_translate("MainWindow", "Pick ARC", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Ch-MPH", None))
        self.checkBox_4.setText(_translate("MainWindow", "Channel 1", None))
        self.pushButton_9.setText(_translate("MainWindow", "Pick recon log", None))
        self.pushButton_10.setText(_translate("MainWindow", "Pick viewEND", None))
        self.pushButton_11.setText(_translate("MainWindow", "Pick SPR", None))
        self.pushButton_12.setText(_translate("MainWindow", "Pick ARC", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Ch-MPH", None))
        self.groupBoxModality.setTitle(_translate("MainWindow", "Imaging modality", None))
        self.radioButtonuCT.setText(_translate("MainWindow", "µCT", None))
        self.radioButtonOPT.setText(_translate("MainWindow", "OPT", None))
        self.groupBoxOptions.setTitle(_translate("MainWindow", "Options", None))
        self.checkBoxPixel.setToolTip(_translate("MainWindow", "You can downsize by pixel. Just put the desired pixel size in the text box.", None))
        self.checkBoxPixel.setText(_translate("MainWindow", "By Pixel (µm)", None))
        self.lineEditX.setText(_translate("MainWindow", "x", None))
        self.lineEditPixel.setToolTip(_translate("MainWindow", "You can downsize by pixel. Just put the desired pixel size in the text box.", None))
        self.label_13.setText(_translate("MainWindow", "Create movie", None))
        self.label_14.setText(_translate("MainWindow", "Cropping", None))
        self.label_5.setText(_translate("MainWindow", "Downsize", None))
        self.label.setText(_translate("MainWindow", "Compression", None))
        self.checkBoxMovie_2.setText(_translate("MainWindow", "Yes", None))
        self.radioButtonNo.setText(_translate("MainWindow", "No crop", None))
        self.radioButtonAuto.setText(_translate("MainWindow", "Automatic", None))
        self.radioButtonMan.setText(_translate("MainWindow", "Manual", None))
        self.checkBoxRF.setText(_translate("MainWindow", "Yes", None))
        self.checkBoxCropComp.setText(_translate("MainWindow", "Cropped recon", None))
        self.checkBoxScansReconComp.setText(_translate("MainWindow", "Scans and original recon", None))
        self.pushButtonGetDimensions.setText(_translate("MainWindow", "Get dimensions", None))
        self.checkBoxSF2.setText(_translate("MainWindow", "2", None))
        self.checkBoxSF3.setText(_translate("MainWindow", "3", None))
        self.checkBoxSF4.setText(_translate("MainWindow", "4", None))
        self.checkBoxSF5.setText(_translate("MainWindow", "5", None))
        self.checkBoxSF6.setText(_translate("MainWindow", "6", None))
        self.lineEditH.setText(_translate("MainWindow", "h", None))
        self.label_2.setText(_translate("MainWindow", "Replace files", None))
        self.lineEditW.setText(_translate("MainWindow", "w", None))
        self.lineEditY.setText(_translate("MainWindow", "y", None))
        self.groupBoxID.setTitle(_translate("MainWindow", "Identification", None))
        self.labelName.setText(_translate("MainWindow", "Full name", None))
        self.lineEditName.setToolTip(_translate("MainWindow", "<html><head/><body><p>You can update the name of recon here and check to see if it is in the right format. </p><p>Each identifier is separated by a underscore _ </p><p>Any additional info can be stored after &quot;rec&quot;:</p><p>[date]_[gene]_[stage]_[litter]_[zygosity]_[sex]_rec_[any additional info]</p></body></html>", None))
        self.pushButtonUpdate.setText(_translate("MainWindow", "Update", None))
        self.labelAge.setText(_translate("MainWindow", "Stage", None))
        self.labelDate.setText(_translate("MainWindow", "Date", None))
        self.labelGroup.setText(_translate("MainWindow", "Gene", None))
        self.labelLitter.setText(_translate("MainWindow", "Litter", None))
        self.labelSex.setText(_translate("MainWindow", "Sex", None))
        self.labelZygosity.setText(_translate("MainWindow", "Zygosity", None))
        self.label_4.setText(_translate("MainWindow", "Name format:\n"
"[date]_[gene]_[stage]_[litter]_[zygosity]_[sex]_rec\n"
"\n"
"Example names:\n"
"20140211_RIC8B_E18.5_16.4a_hom_XX_rec\n"
"20140211_RIC8B_E18.5_16.4a_hom_NA_rec", None))
        self.groupBoxModality_2.setTitle(_translate("MainWindow", "Status", None))
        self.groupBoxReconInfo.setTitle(_translate("MainWindow", "Recon File Info", None))
        self.labelPixel.setText(_translate("MainWindow", "Pixel size (µm)", None))
        self.lcdNumberPixel.setToolTip(_translate("MainWindow", "This is the pixel size of the original recon", None))
        self.lcdNumberFile.setToolTip(_translate("MainWindow", "This is the approximate folder size of the original recon", None))
        self.labelFile.setText(_translate("MainWindow", "Folder size (Mb)", None))
        self.groupBoxuCTOnly.setTitle(_translate("MainWindow", "µCT only", None))
        self.pushButtonCTRecon.setText(_translate("MainWindow", "Pick recon log", None))
        self.pushButtonCTSPR.setText(_translate("MainWindow", "Pick SPR", None))
        self.pushButtonCTARC.setText(_translate("MainWindow", "Pick ARC", None))
        self.comboBoxCh.setItemText(0, _translate("MainWindow", "Ch-X", None))
        self.pushButtonScan.setText(_translate("MainWindow", "Scan folder", None))
        self.pushButtonOutput.setText(_translate("MainWindow", "Output folder", None))
        self.pushButtonInput.setText(_translate("MainWindow", "Input folder", None))
        self.pushButtonGo.setText(_translate("MainWindow", "Add to Processing List", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Parameters", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Original Name", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Output", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Start Time", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Finish Time", None))
        self.pushButtonStart.setText(_translate("MainWindow", "Start", None))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop", None))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add More", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Processing", None))
        self.menuMore_Options.setTitle(_translate("MainWindow", "More Options", None))
        self.actionChange_ID.setText(_translate("MainWindow", "Allow identification to be changed", None))
        self.actionManually_select_output_folder.setText(_translate("MainWindow", "Allow manually selection of output folder", None))
        self.actionAccurate_folder_size_calculation.setText(_translate("MainWindow", "Accurate folder size calculation", None))
        self.actionResize.setText(_translate("MainWindow", "Resize screen for small monitors", None))
        self.actionReset_screen_size.setText(_translate("MainWindow", "Reset screen size", None))

