# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Progress.ui'
#
# Created: Tue Feb 18 16:51:25 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Progress(object):
    def setupUi(self, Progress):
        Progress.setObjectName(_fromUtf8("Progress"))
        Progress.resize(842, 287)
        self.gridLayoutWidget = QtGui.QWidget(Progress)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 90, 761, 161))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.progressBar_5 = QtGui.QProgressBar(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar_5.setFont(font)
        self.progressBar_5.setProperty("value", 35)
        self.progressBar_5.setObjectName(_fromUtf8("progressBar_5"))
        self.gridLayout.addWidget(self.progressBar_5, 0, 1, 1, 1)
        self.progressBar_3 = QtGui.QProgressBar(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar_3.setFont(font)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.gridLayout.addWidget(self.progressBar_3, 2, 1, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 4, 1, 1, 1)
        self.pushButton_1 = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName(_fromUtf8("pushButton_1"))
        self.gridLayout.addWidget(self.pushButton_1, 0, 2, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 3, 2, 1, 1)
        self.progressBar_2 = QtGui.QProgressBar(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar_2.setFont(font)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.gridLayout.addWidget(self.progressBar_2, 3, 1, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout.addWidget(self.pushButton_5, 4, 2, 1, 1)
        self.progressBar_4 = QtGui.QProgressBar(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar_4.setFont(font)
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setObjectName(_fromUtf8("progressBar_4"))
        self.gridLayout.addWidget(self.progressBar_4, 1, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(Progress)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 10, 761, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))

        self.retranslateUi(Progress)
        QtCore.QMetaObject.connectSlotsByName(Progress)

    def retranslateUi(self, Progress):
        Progress.setWindowTitle(_translate("Progress", "Track progress", None))
        self.pushButton_1.setText(_translate("Progress", "Cancel", None))
        self.pushButton_3.setText(_translate("Progress", "Cancel", None))
        self.pushButton_4.setText(_translate("Progress", "Cancel", None))
        self.pushButton_5.setText(_translate("Progress", "Cancel", None))
        self.pushButton_2.setText(_translate("Progress", "Cancel", None))
        self.label.setText(_translate("Progress", "20131206_MLLT3_15.3_d_WT_rec", None))
        self.label_2.setText(_translate("Progress", "20131206_CBX_15.3_d_WT_rec", None))
        self.label_3.setText(_translate("Progress", "20131206_FFS1A_15.3_d_WT_rec", None))
        self.label_4.setText(_translate("Progress", "20131206_MLLT5_15.3_d_WT_rec", None))
        self.label_5.setText(_translate("Progress", "20131206_PLA1_15.3_d_WT_rec", None))
        self.pushButton_6.setText(_translate("Progress", "Add another recon to process (max 10?)", None))

