# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Progress.ui'
#
# Created: Fri Mar  7 09:53:38 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Progress(object):
    def setupUi(self, Progress):
        Progress.setObjectName(_fromUtf8("Progress"))
        Progress.resize(842, 396)
        self.gridLayoutWidget = QtGui.QWidget(Progress)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 90, 761, 276))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.pushButtonCancel_3 = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCancel_3.setFont(font)
        self.pushButtonCancel_3.setObjectName(_fromUtf8("pushButtonCancel_3"))
        self.gridLayout.addWidget(self.pushButtonCancel_3, 4, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.pushButtonCancel_2 = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCancel_2.setFont(font)
        self.pushButtonCancel_2.setObjectName(_fromUtf8("pushButtonCancel_2"))
        self.gridLayout.addWidget(self.pushButtonCancel_2, 2, 2, 1, 1)
        self.label2_Tracking = QtGui.QLabel(self.gridLayoutWidget)
        self.label2_Tracking.setAlignment(QtCore.Qt.AlignCenter)
        self.label2_Tracking.setObjectName(_fromUtf8("label2_Tracking"))
        self.gridLayout.addWidget(self.label2_Tracking, 3, 1, 1, 1)
        self.label4_Tracking = QtGui.QLabel(self.gridLayoutWidget)
        self.label4_Tracking.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_Tracking.setObjectName(_fromUtf8("label4_Tracking"))
        self.gridLayout.addWidget(self.label4_Tracking, 7, 1, 1, 1)
        self.label1_tracking = QtGui.QLabel(self.gridLayoutWidget)
        self.label1_tracking.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_tracking.setObjectName(_fromUtf8("label1_tracking"))
        self.gridLayout.addWidget(self.label1_tracking, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.progressBar_4 = QtGui.QProgressBar(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar_4.setFont(font)
        self.progressBar_4.setMinimum(0)
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setObjectName(_fromUtf8("progressBar_4"))
        self.gridLayout.addWidget(self.progressBar_4, 2, 1, 1, 1)
        self.pushButtonCancel_4 = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCancel_4.setFont(font)
        self.pushButtonCancel_4.setObjectName(_fromUtf8("pushButtonCancel_4"))
        self.gridLayout.addWidget(self.pushButtonCancel_4, 6, 2, 1, 1)
        self.pushButtonCancel_1 = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCancel_1.setFont(font)
        self.pushButtonCancel_1.setObjectName(_fromUtf8("pushButtonCancel_1"))
        self.gridLayout.addWidget(self.pushButtonCancel_1, 0, 2, 1, 1)
        self.pushButtonCancel_5 = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCancel_5.setFont(font)
        self.pushButtonCancel_5.setObjectName(_fromUtf8("pushButtonCancel_5"))
        self.gridLayout.addWidget(self.pushButtonCancel_5, 8, 2, 1, 1)
        self.label_1 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.progressBar_2 = QtGui.QProgressBar(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar_2.setFont(font)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.gridLayout.addWidget(self.progressBar_2, 6, 1, 1, 1)
        self.label3_Tracking = QtGui.QLabel(self.gridLayoutWidget)
        self.label3_Tracking.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_Tracking.setObjectName(_fromUtf8("label3_Tracking"))
        self.gridLayout.addWidget(self.label3_Tracking, 5, 1, 1, 1)
        self.progressBar_5 = QtGui.QProgressBar(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar_5.setFont(font)
        self.progressBar_5.setMinimum(0)
        self.progressBar_5.setProperty("value", 0)
        self.progressBar_5.setObjectName(_fromUtf8("progressBar_5"))
        self.gridLayout.addWidget(self.progressBar_5, 8, 1, 1, 1)
        self.progressBar_1 = QtGui.QProgressBar(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar_1.setFont(font)
        self.progressBar_1.setProperty("value", 0)
        self.progressBar_1.setObjectName(_fromUtf8("progressBar_1"))
        self.gridLayout.addWidget(self.progressBar_1, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.progressBar_3 = QtGui.QProgressBar(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar_3.setFont(font)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.gridLayout.addWidget(self.progressBar_3, 4, 1, 1, 1)
        self.label5_Tracking = QtGui.QLabel(self.gridLayoutWidget)
        self.label5_Tracking.setAlignment(QtCore.Qt.AlignCenter)
        self.label5_Tracking.setObjectName(_fromUtf8("label5_Tracking"))
        self.gridLayout.addWidget(self.label5_Tracking, 9, 1, 1, 1)
        self.pushButtonAddMore = QtGui.QPushButton(Progress)
        self.pushButtonAddMore.setGeometry(QtCore.QRect(30, 10, 761, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonAddMore.setFont(font)
        self.pushButtonAddMore.setObjectName(_fromUtf8("pushButtonAddMore"))

        self.retranslateUi(Progress)
        QtCore.QMetaObject.connectSlotsByName(Progress)

    def retranslateUi(self, Progress):
        Progress.setWindowTitle(_translate("Progress", "Track progress", None))
        self.label_5.setText(_translate("Progress", "...", None))
        self.pushButtonCancel_3.setText(_translate("Progress", "Cancel", None))
        self.label_4.setText(_translate("Progress", "...", None))
        self.pushButtonCancel_2.setText(_translate("Progress", "Cancel", None))
        self.label2_Tracking.setText(_translate("Progress", "...", None))
        self.label4_Tracking.setText(_translate("Progress", "...", None))
        self.label1_tracking.setText(_translate("Progress", "...", None))
        self.label_2.setText(_translate("Progress", "...", None))
        self.pushButtonCancel_4.setText(_translate("Progress", "Cancel", None))
        self.pushButtonCancel_1.setText(_translate("Progress", "Cancel", None))
        self.pushButtonCancel_5.setText(_translate("Progress", "Cancel", None))
        self.label_1.setText(_translate("Progress", "...", None))
        self.label3_Tracking.setText(_translate("Progress", "...", None))
        self.label_3.setText(_translate("Progress", "...", None))
        self.label5_Tracking.setText(_translate("Progress", "...", None))
        self.pushButtonAddMore.setText(_translate("Progress", "Add another recon to process", None))

