# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_new.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1438, 1007)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1382, 958))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBoxModality = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxModality.setFont(font)
        self.groupBoxModality.setStyleSheet("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;\n"
"}")
        self.groupBoxModality.setObjectName("groupBoxModality")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxModality)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButtonuCT = QtWidgets.QRadioButton(self.groupBoxModality)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonuCT.setFont(font)
        self.radioButtonuCT.setChecked(True)
        self.radioButtonuCT.setObjectName("radioButtonuCT")
        self.gridLayout_3.addWidget(self.radioButtonuCT, 1, 0, 1, 1)
        self.radioButtonOPT = QtWidgets.QRadioButton(self.groupBoxModality)
        self.radioButtonOPT.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonOPT.setFont(font)
        self.radioButtonOPT.setObjectName("radioButtonOPT")
        self.gridLayout_3.addWidget(self.radioButtonOPT, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxModality, 0, 1, 1, 1)
        self.gridLayoutFileSelect = QtWidgets.QGridLayout()
        self.gridLayoutFileSelect.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayoutFileSelect.setObjectName("gridLayoutFileSelect")
        self.pushButtonOutput = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonOutput.setFont(font)
        self.pushButtonOutput.setObjectName("pushButtonOutput")
        self.gridLayoutFileSelect.addWidget(self.pushButtonOutput, 1, 0, 1, 1)
        self.lineEditInput = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditInput.setFont(font)
        self.lineEditInput.setObjectName("lineEditInput")
        self.gridLayoutFileSelect.addWidget(self.lineEditInput, 0, 1, 1, 1)
        self.lineEditOutput = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditOutput.setFont(font)
        self.lineEditOutput.setObjectName("lineEditOutput")
        self.gridLayoutFileSelect.addWidget(self.lineEditOutput, 1, 1, 1, 1)
        self.pushButtonInput = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonInput.setFont(font)
        self.pushButtonInput.setObjectName("pushButtonInput")
        self.gridLayoutFileSelect.addWidget(self.pushButtonInput, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayoutFileSelect, 0, 0, 1, 1)
        self.pushButtonGo = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButtonGo.setMinimumSize(QtCore.QSize(0, 65))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonGo.setFont(font)
        self.pushButtonGo.setDefault(False)
        self.pushButtonGo.setObjectName("pushButtonGo")
        self.gridLayout_2.addWidget(self.pushButtonGo, 16, 0, 1, 2)
        self.groupBoxReconInfo = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxReconInfo.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxReconInfo.setFont(font)
        self.groupBoxReconInfo.setAutoFillBackground(False)
        self.groupBoxReconInfo.setStyleSheet("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;\n"
"}")
        self.groupBoxReconInfo.setFlat(False)
        self.groupBoxReconInfo.setCheckable(False)
        self.groupBoxReconInfo.setObjectName("groupBoxReconInfo")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBoxReconInfo)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayoutReconInfo = QtWidgets.QGridLayout()
        self.gridLayoutReconInfo.setObjectName("gridLayoutReconInfo")
        self.labelPixel = QtWidgets.QLabel(self.groupBoxReconInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPixel.setFont(font)
        self.labelPixel.setObjectName("labelPixel")
        self.gridLayoutReconInfo.addWidget(self.labelPixel, 0, 2, 1, 1)
        self.lcdNumberPixel = QtWidgets.QLCDNumber(self.groupBoxReconInfo)
        self.lcdNumberPixel.setSmallDecimalPoint(True)
        self.lcdNumberPixel.setDigitCount(7)
        self.lcdNumberPixel.setProperty("value", 0.0)
        self.lcdNumberPixel.setObjectName("lcdNumberPixel")
        self.gridLayoutReconInfo.addWidget(self.lcdNumberPixel, 0, 3, 1, 1)
        self.lcdNumberFile = QtWidgets.QLCDNumber(self.groupBoxReconInfo)
        self.lcdNumberFile.setSmallDecimalPoint(True)
        self.lcdNumberFile.setDigitCount(7)
        self.lcdNumberFile.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumberFile.setObjectName("lcdNumberFile")
        self.gridLayoutReconInfo.addWidget(self.lcdNumberFile, 0, 1, 1, 1)
        self.labelFile = QtWidgets.QLabel(self.groupBoxReconInfo)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelFile.setFont(font)
        self.labelFile.setObjectName("labelFile")
        self.gridLayoutReconInfo.addWidget(self.labelFile, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayoutReconInfo, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxReconInfo, 8, 0, 1, 1)
        self.groupBoxOptions = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxOptions.setFont(font)
        self.groupBoxOptions.setStyleSheet("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;\n"
"}")
        self.groupBoxOptions.setObjectName("groupBoxOptions")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxOptions)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line_2 = QtWidgets.QFrame(self.groupBoxOptions)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 19, 0, 1, 5)
        self.line = QtWidgets.QFrame(self.groupBoxOptions)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 17, 0, 1, 5)
        self.radioButtonMan = QtWidgets.QRadioButton(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setItalic(False)
        self.radioButtonMan.setFont(font)
        self.radioButtonMan.setChecked(False)
        self.radioButtonMan.setObjectName("radioButtonMan")
        self.gridLayout_4.addWidget(self.radioButtonMan, 6, 1, 1, 1)
        self.radioButtonAuto = QtWidgets.QRadioButton(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setItalic(False)
        self.radioButtonAuto.setFont(font)
        self.radioButtonAuto.setChecked(True)
        self.radioButtonAuto.setObjectName("radioButtonAuto")
        self.gridLayout_4.addWidget(self.radioButtonAuto, 1, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBoxOptions)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 14, 0, 1, 5)
        self.label_zwait = QtWidgets.QLabel(self.groupBoxOptions)
        self.label_zwait.setText("")
        self.label_zwait.setObjectName("label_zwait")
        self.gridLayout_4.addWidget(self.label_zwait, 16, 2, 1, 1)
        self.checkBoxCropYes = QtWidgets.QCheckBox(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxCropYes.setFont(font)
        self.checkBoxCropYes.setChecked(True)
        self.checkBoxCropYes.setObjectName("checkBoxCropYes")
        self.gridLayout_4.addWidget(self.checkBoxCropYes, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBoxOptions)
        self.label_3.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 15, 0, 1, 1)
        self.checkBoxRF = QtWidgets.QCheckBox(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxRF.setFont(font)
        self.checkBoxRF.setObjectName("checkBoxRF")
        self.gridLayout_4.addWidget(self.checkBoxRF, 20, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 20, 0, 1, 1)
        self.checkBoxMovie_2 = QtWidgets.QCheckBox(self.groupBoxOptions)
        self.checkBoxMovie_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxMovie_2.setFont(font)
        self.checkBoxMovie_2.setObjectName("checkBoxMovie_2")
        self.gridLayout_4.addWidget(self.checkBoxMovie_2, 16, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBoxOptions)
        self.label.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 18, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBoxOptions)
        self.label_13.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 16, 0, 1, 1)
        self.checkBoxMask = QtWidgets.QCheckBox(self.groupBoxOptions)
        self.checkBoxMask.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxMask.setFont(font)
        self.checkBoxMask.setObjectName("checkBoxMask")
        self.gridLayout_4.addWidget(self.checkBoxMask, 15, 1, 1, 1)
        self.lineEditH = QtWidgets.QLineEdit(self.groupBoxOptions)
        self.lineEditH.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditH.setFont(font)
        self.lineEditH.setObjectName("lineEditH")
        self.gridLayout_4.addWidget(self.lineEditH, 8, 4, 1, 1)
        self.lineEditY = QtWidgets.QLineEdit(self.groupBoxOptions)
        self.lineEditY.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditY.setFont(font)
        self.lineEditY.setObjectName("lineEditY")
        self.gridLayout_4.addWidget(self.lineEditY, 8, 2, 1, 1)
        self.lineEditX = QtWidgets.QLineEdit(self.groupBoxOptions)
        self.lineEditX.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditX.setFont(font)
        self.lineEditX.setReadOnly(False)
        self.lineEditX.setObjectName("lineEditX")
        self.gridLayout_4.addWidget(self.lineEditX, 8, 1, 1, 1)
        self.pushButtonGetDimensions = QtWidgets.QPushButton(self.groupBoxOptions)
        self.pushButtonGetDimensions.setEnabled(False)
        self.pushButtonGetDimensions.setCheckable(False)
        self.pushButtonGetDimensions.setObjectName("pushButtonGetDimensions")
        self.gridLayout_4.addWidget(self.pushButtonGetDimensions, 7, 1, 1, 4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem3, 9, 1, 1, 1)
        self.lineEditW = QtWidgets.QLineEdit(self.groupBoxOptions)
        self.lineEditW.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditW.setFont(font)
        self.lineEditW.setObjectName("lineEditW")
        self.gridLayout_4.addWidget(self.lineEditW, 8, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 1)
        self.radioButtonDerived = QtWidgets.QRadioButton(self.groupBoxOptions)
        self.radioButtonDerived.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonDerived.setFont(font)
        self.radioButtonDerived.setObjectName("radioButtonDerived")
        self.gridLayout_4.addWidget(self.radioButtonDerived, 2, 1, 1, 1)
        self.radioButtonUseOldCrop = QtWidgets.QRadioButton(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonUseOldCrop.setFont(font)
        self.radioButtonUseOldCrop.setObjectName("radioButtonUseOldCrop")
        self.gridLayout_4.addWidget(self.radioButtonUseOldCrop, 5, 1, 1, 1)
        self.lineEditDerivedChnName = QtWidgets.QLineEdit(self.groupBoxOptions)
        self.lineEditDerivedChnName.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditDerivedChnName.setFont(font)
        self.lineEditDerivedChnName.setReadOnly(True)
        self.lineEditDerivedChnName.setObjectName("lineEditDerivedChnName")
        self.gridLayout_4.addWidget(self.lineEditDerivedChnName, 2, 2, 1, 3)
        self.line_3 = QtWidgets.QFrame(self.groupBoxOptions)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 10, 0, 1, 5)
        self.checkBoxCropComp = QtWidgets.QCheckBox(self.groupBoxOptions)
        self.checkBoxCropComp.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxCropComp.setFont(font)
        self.checkBoxCropComp.setObjectName("checkBoxCropComp")
        self.gridLayout_4.addWidget(self.checkBoxCropComp, 18, 3, 1, 1)
        self.pushButtonIMPC = QtWidgets.QPushButton(self.groupBoxOptions)
        self.pushButtonIMPC.setStyleSheet("    color: #020202;\n"
"    background-color: #d7801a;\n"
"    border-style: none;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    outline: none;")
        self.pushButtonIMPC.setObjectName("pushButtonIMPC")
        self.gridLayout_4.addWidget(self.pushButtonIMPC, 18, 4, 1, 1)
        self.checkBoxCreateStack = QtWidgets.QCheckBox(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.checkBoxCreateStack.setFont(font)
        self.checkBoxCreateStack.setObjectName("checkBoxCreateStack")
        self.gridLayout_4.addWidget(self.checkBoxCreateStack, 1, 2, 1, 1)
        self.comboBoxStackType = QtWidgets.QComboBox(self.groupBoxOptions)
        self.comboBoxStackType.setEnabled(False)
        self.comboBoxStackType.setMaxVisibleItems(10)
        self.comboBoxStackType.setMinimumContentsLength(0)
        self.comboBoxStackType.setObjectName("comboBoxStackType")
        self.comboBoxStackType.addItem("")
        self.comboBoxStackType.addItem("")
        self.gridLayout_4.addWidget(self.comboBoxStackType, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 11, 3, 1, 1)
        self.checkBoxScansReconComp = QtWidgets.QCheckBox(self.groupBoxOptions)
        self.checkBoxScansReconComp.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxScansReconComp.setFont(font)
        self.checkBoxScansReconComp.setObjectName("checkBoxScansReconComp")
        self.gridLayout_4.addWidget(self.checkBoxScansReconComp, 18, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 11, 0, 1, 1)
        self.integerFactors = QtWidgets.QHBoxLayout()
        self.integerFactors.setObjectName("integerFactors")
        self.checkBoxSF2 = QtWidgets.QCheckBox(self.groupBoxOptions)
        self.checkBoxSF2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxSF2.setFont(font)
        self.checkBoxSF2.setChecked(True)
        self.checkBoxSF2.setObjectName("checkBoxSF2")
        self.integerFactors.addWidget(self.checkBoxSF2)
        self.checkBoxSF3 = QtWidgets.QCheckBox(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxSF3.setFont(font)
        self.checkBoxSF3.setChecked(False)
        self.checkBoxSF3.setObjectName("checkBoxSF3")
        self.integerFactors.addWidget(self.checkBoxSF3)
        self.checkBoxSF4 = QtWidgets.QCheckBox(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxSF4.setFont(font)
        self.checkBoxSF4.setChecked(False)
        self.checkBoxSF4.setObjectName("checkBoxSF4")
        self.integerFactors.addWidget(self.checkBoxSF4)
        self.checkBoxSF5 = QtWidgets.QCheckBox(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxSF5.setFont(font)
        self.checkBoxSF5.setChecked(False)
        self.checkBoxSF5.setObjectName("checkBoxSF5")
        self.integerFactors.addWidget(self.checkBoxSF5)
        self.checkBoxSF6 = QtWidgets.QCheckBox(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxSF6.setFont(font)
        self.checkBoxSF6.setChecked(False)
        self.checkBoxSF6.setObjectName("checkBoxSF6")
        self.integerFactors.addWidget(self.checkBoxSF6)
        self.gridLayout_4.addLayout(self.integerFactors, 12, 1, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidgetPixelScales = QtWidgets.QTableWidget(self.groupBoxOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetPixelScales.sizePolicy().hasHeightForWidth())
        self.tableWidgetPixelScales.setSizePolicy(sizePolicy)
        self.tableWidgetPixelScales.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidgetPixelScales.setFont(font)
        self.tableWidgetPixelScales.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidgetPixelScales.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidgetPixelScales.setShowGrid(True)
        self.tableWidgetPixelScales.setObjectName("tableWidgetPixelScales")
        self.tableWidgetPixelScales.setColumnCount(1)
        self.tableWidgetPixelScales.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPixelScales.setHorizontalHeaderItem(0, item)
        self.tableWidgetPixelScales.horizontalHeader().setVisible(False)
        self.tableWidgetPixelScales.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidgetPixelScales.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetPixelScales.verticalHeader().setVisible(False)
        self.tableWidgetPixelScales.verticalHeader().setDefaultSectionSize(17)
        self.tableWidgetPixelScales.verticalHeader().setMinimumSectionSize(14)
        self.horizontalLayout_3.addWidget(self.tableWidgetPixelScales)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.spinPixelSize = QtWidgets.QDoubleSpinBox(self.groupBoxOptions)
        self.spinPixelSize.setProperty("value", 14.0)
        self.spinPixelSize.setObjectName("spinPixelSize")
        self.verticalLayout_3.addWidget(self.spinPixelSize)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonAddPixelSize = QtWidgets.QPushButton(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonAddPixelSize.setFont(font)
        self.buttonAddPixelSize.setObjectName("buttonAddPixelSize")
        self.horizontalLayout_5.addWidget(self.buttonAddPixelSize)
        self.buttonRemovePixelSize = QtWidgets.QPushButton(self.groupBoxOptions)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonRemovePixelSize.setFont(font)
        self.buttonRemovePixelSize.setObjectName("buttonRemovePixelSize")
        self.horizontalLayout_5.addWidget(self.buttonRemovePixelSize)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 12, 3, 1, 2)
        self.checkBoxReprocessToRas = QtWidgets.QCheckBox(self.groupBoxOptions)
        self.checkBoxReprocessToRas.setObjectName("checkBoxReprocessToRas")
        self.gridLayout_4.addWidget(self.checkBoxReprocessToRas, 20, 4, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 2, 0, 2, 2)
        self.gridLayout_2.addWidget(self.groupBoxOptions, 8, 1, 2, 1)
        self.groupBoxID = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxID.setFont(font)
        self.groupBoxID.setStyleSheet("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;\n"
"}")
        self.groupBoxID.setObjectName("groupBoxID")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBoxID)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem4, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayoutIDs = QtWidgets.QGridLayout()
        self.gridLayoutIDs.setObjectName("gridLayoutIDs")
        self.labelAge = QtWidgets.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelAge.setFont(font)
        self.labelAge.setObjectName("labelAge")
        self.gridLayoutIDs.addWidget(self.labelAge, 0, 4, 1, 1)
        self.lineEditGroup = QtWidgets.QLineEdit(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditGroup.setFont(font)
        self.lineEditGroup.setReadOnly(True)
        self.lineEditGroup.setObjectName("lineEditGroup")
        self.gridLayoutIDs.addWidget(self.lineEditGroup, 0, 3, 1, 1)
        self.lineEditDate = QtWidgets.QLineEdit(self.groupBoxID)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditDate.sizePolicy().hasHeightForWidth())
        self.lineEditDate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditDate.setFont(font)
        self.lineEditDate.setText("")
        self.lineEditDate.setReadOnly(True)
        self.lineEditDate.setObjectName("lineEditDate")
        self.gridLayoutIDs.addWidget(self.lineEditDate, 0, 1, 1, 1)
        self.lineEditAge = QtWidgets.QLineEdit(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditAge.setFont(font)
        self.lineEditAge.setReadOnly(True)
        self.lineEditAge.setObjectName("lineEditAge")
        self.gridLayoutIDs.addWidget(self.lineEditAge, 0, 5, 1, 1)
        self.labelDate = QtWidgets.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelDate.setFont(font)
        self.labelDate.setObjectName("labelDate")
        self.gridLayoutIDs.addWidget(self.labelDate, 0, 0, 1, 1)
        self.labelGroup = QtWidgets.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelGroup.setFont(font)
        self.labelGroup.setObjectName("labelGroup")
        self.gridLayoutIDs.addWidget(self.labelGroup, 0, 2, 1, 1)
        self.lineEditZygosity = QtWidgets.QLineEdit(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditZygosity.setFont(font)
        self.lineEditZygosity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditZygosity.setReadOnly(True)
        self.lineEditZygosity.setObjectName("lineEditZygosity")
        self.gridLayoutIDs.addWidget(self.lineEditZygosity, 1, 3, 1, 1)
        self.labelZygosity = QtWidgets.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelZygosity.setFont(font)
        self.labelZygosity.setObjectName("labelZygosity")
        self.gridLayoutIDs.addWidget(self.labelZygosity, 1, 2, 1, 1)
        self.labelSex = QtWidgets.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelSex.setFont(font)
        self.labelSex.setObjectName("labelSex")
        self.gridLayoutIDs.addWidget(self.labelSex, 1, 4, 1, 1)
        self.labelChannel = QtWidgets.QLabel(self.groupBoxID)
        self.labelChannel.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelChannel.setFont(font)
        self.labelChannel.setObjectName("labelChannel")
        self.gridLayoutIDs.addWidget(self.labelChannel, 2, 0, 1, 1)
        self.lineEditChannel = QtWidgets.QLineEdit(self.groupBoxID)
        self.lineEditChannel.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditChannel.setFont(font)
        self.lineEditChannel.setReadOnly(True)
        self.lineEditChannel.setObjectName("lineEditChannel")
        self.gridLayoutIDs.addWidget(self.lineEditChannel, 2, 1, 1, 1)
        self.lineEditLitter = QtWidgets.QLineEdit(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditLitter.setFont(font)
        self.lineEditLitter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditLitter.setText("")
        self.lineEditLitter.setReadOnly(True)
        self.lineEditLitter.setObjectName("lineEditLitter")
        self.gridLayoutIDs.addWidget(self.lineEditLitter, 1, 1, 1, 1)
        self.labelLitter = QtWidgets.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelLitter.setFont(font)
        self.labelLitter.setObjectName("labelLitter")
        self.gridLayoutIDs.addWidget(self.labelLitter, 1, 0, 1, 1)
        self.lineEditSex = QtWidgets.QLineEdit(self.groupBoxID)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        self.lineEditSex.setFont(font)
        self.lineEditSex.setReadOnly(True)
        self.lineEditSex.setObjectName("lineEditSex")
        self.gridLayoutIDs.addWidget(self.lineEditSex, 1, 5, 1, 1)
        self.labelName = QtWidgets.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.gridLayoutIDs.addWidget(self.labelName, 3, 0, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditName.setFont(font)
        self.lineEditName.setReadOnly(False)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayoutIDs.addWidget(self.lineEditName, 3, 1, 1, 4)
        self.pushButtonUpdate = QtWidgets.QPushButton(self.groupBoxID)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        self.pushButtonUpdate.setFont(font)
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.gridLayoutIDs.addWidget(self.pushButtonUpdate, 3, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayoutIDs)
        self.gridLayout_6.addLayout(self.verticalLayout, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem5, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        spacerItem6 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.label_6 = QtWidgets.QLabel(self.groupBoxID)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 6, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxID, 9, 0, 2, 1)
        self.groupBoxuCTOnly = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxuCTOnly.setMaximumSize(QtCore.QSize(16777215, 600))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxuCTOnly.setFont(font)
        self.groupBoxuCTOnly.setStyleSheet("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;\n"
"}")
        self.groupBoxuCTOnly.setFlat(False)
        self.groupBoxuCTOnly.setCheckable(False)
        self.groupBoxuCTOnly.setChecked(False)
        self.groupBoxuCTOnly.setObjectName("groupBoxuCTOnly")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBoxuCTOnly)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.formLayoutuCTOnly = QtWidgets.QFormLayout()
        self.formLayoutuCTOnly.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayoutuCTOnly.setObjectName("formLayoutuCTOnly")
        self.pushButtonCTRecon = QtWidgets.QPushButton(self.groupBoxuCTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCTRecon.setFont(font)
        self.pushButtonCTRecon.setObjectName("pushButtonCTRecon")
        self.formLayoutuCTOnly.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButtonCTRecon)
        self.lineEditCTRecon = QtWidgets.QLineEdit(self.groupBoxuCTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditCTRecon.setFont(font)
        self.lineEditCTRecon.setObjectName("lineEditCTRecon")
        self.formLayoutuCTOnly.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditCTRecon)
        self.pushButtonCTSPR = QtWidgets.QPushButton(self.groupBoxuCTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCTSPR.setFont(font)
        self.pushButtonCTSPR.setObjectName("pushButtonCTSPR")
        self.formLayoutuCTOnly.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButtonCTSPR)
        self.lineEditCTSPR = QtWidgets.QLineEdit(self.groupBoxuCTOnly)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditCTSPR.setFont(font)
        self.lineEditCTSPR.setObjectName("lineEditCTSPR")
        self.formLayoutuCTOnly.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditCTSPR)
        self.pushButtonScan = QtWidgets.QPushButton(self.groupBoxuCTOnly)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        self.pushButtonScan.setFont(font)
        self.pushButtonScan.setObjectName("pushButtonScan")
        self.formLayoutuCTOnly.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButtonScan)
        self.lineEditScan = QtWidgets.QLineEdit(self.groupBoxuCTOnly)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        self.lineEditScan.setFont(font)
        self.lineEditScan.setObjectName("lineEditScan")
        self.formLayoutuCTOnly.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditScan)
        self.gridLayout_8.addLayout(self.formLayoutuCTOnly, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem8, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxuCTOnly, 11, 0, 1, 1)
        self.groupBoxModality_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxModality_2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxModality_2.setFont(font)
        self.groupBoxModality_2.setStyleSheet("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;\n"
"}")
        self.groupBoxModality_2.setObjectName("groupBoxModality_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBoxModality_2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_12.addItem(spacerItem9, 0, 0, 1, 1)
        self.textEditStatusMessages = QtWidgets.QTextEdit(self.groupBoxModality_2)
        self.textEditStatusMessages.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textEditStatusMessages.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        self.textEditStatusMessages.setFont(font)
        self.textEditStatusMessages.setObjectName("textEditStatusMessages")
        self.gridLayout_12.addWidget(self.textEditStatusMessages, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxModality_2, 12, 0, 1, 1)
        self.groupBoxOPTChannels = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxOPTChannels.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBoxOPTChannels.setFont(font)
        self.groupBoxOPTChannels.setStyleSheet("QGroupBox\n"
"{\n"
"    background-color:transparent;\n"
"    border: 1px solid #acacac;\n"
"    margin-top: 5px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    subcontrol-origin: margin;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border: 1px solid #0b477b;\n"
"    border-bottom: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #005192, stop: 1 #002f60);\n"
"    padding: 2 2px;\n"
"    color: white;\n"
"}")
        self.groupBoxOPTChannels.setObjectName("groupBoxOPTChannels")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.groupBoxOPTChannels)
        self.scrollArea_3.setGeometry(QtCore.QRect(10, 40, 581, 201))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 579, 199))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.tableWidgetOPT = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_3)
        self.tableWidgetOPT.setEnabled(False)
        self.tableWidgetOPT.setGeometry(QtCore.QRect(10, 10, 561, 181))
        self.tableWidgetOPT.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidgetOPT.setAlternatingRowColors(True)
        self.tableWidgetOPT.setObjectName("tableWidgetOPT")
        self.tableWidgetOPT.setColumnCount(3)
        self.tableWidgetOPT.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 0, 0))
        self.tableWidgetOPT.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOPT.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOPT.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOPT.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOPT.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOPT.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOPT.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOPT.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOPT.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOPT.setHorizontalHeaderItem(2, item)
        self.tableWidgetOPT.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidgetOPT.verticalHeader().setStretchLastSection(True)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.checkBoxInd = QtWidgets.QCheckBox(self.groupBoxOPTChannels)
        self.checkBoxInd.setEnabled(False)
        self.checkBoxInd.setGeometry(QtCore.QRect(390, 10, 161, 20))
        self.checkBoxInd.setObjectName("checkBoxInd")
        self.gridLayout_2.addWidget(self.groupBoxOPTChannels, 10, 1, 3, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 88, 88))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_9.addWidget(self.scrollArea_2, 7, 0, 1, 3)
        self.pushButtonStart = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.gridLayout_9.addWidget(self.pushButtonStart, 6, 0, 1, 1)
        self.pushButtonStop = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonStop.setEnabled(False)
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.gridLayout_9.addWidget(self.pushButtonStop, 6, 1, 1, 1)
        self.pushButtonAdd = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.gridLayout_9.addWidget(self.pushButtonAdd, 6, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser.setGeometry(QtCore.QRect(30, 10, 351, 171))
        self.textBrowser.setObjectName("textBrowser")
        self.textEditIgnoreFiles = QtWidgets.QTextEdit(self.tab_3)
        self.textEditIgnoreFiles.setGeometry(QtCore.QRect(30, 190, 351, 75))
        self.textEditIgnoreFiles.setObjectName("textEditIgnoreFiles")
        self.pushButtonSaveOptions = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonSaveOptions.setGeometry(QtCore.QRect(340, 380, 96, 31))
        self.pushButtonSaveOptions.setObjectName("pushButtonSaveOptions")
        self.pushButtonResetIgnoreFiles = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonResetIgnoreFiles.setGeometry(QtCore.QRect(140, 280, 96, 31))
        self.pushButtonResetIgnoreFiles.setObjectName("pushButtonResetIgnoreFiles")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_2.setGeometry(QtCore.QRect(390, 10, 351, 171))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textEditUseFile = QtWidgets.QTextEdit(self.tab_3)
        self.textEditUseFile.setGeometry(QtCore.QRect(390, 190, 351, 75))
        self.textEditUseFile.setObjectName("textEditUseFile")
        self.pushButtonResetUSeFiles = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonResetUSeFiles.setGeometry(QtCore.QRect(520, 280, 96, 31))
        self.pushButtonResetUSeFiles.setObjectName("pushButtonResetUSeFiles")
        self.checkBoxSuppressNameWarnings = QtWidgets.QCheckBox(self.tab_3)
        self.checkBoxSuppressNameWarnings.setGeometry(QtCore.QRect(770, 10, 251, 26))
        self.checkBoxSuppressNameWarnings.setObjectName("checkBoxSuppressNameWarnings")
        self.checkBoxSuppressModalityWarning = QtWidgets.QCheckBox(self.tab_3)
        self.checkBoxSuppressModalityWarning.setGeometry(QtCore.QRect(770, 50, 251, 26))
        self.checkBoxSuppressModalityWarning.setObjectName("checkBoxSuppressModalityWarning")
        self.groupBoxCenter = QtWidgets.QGroupBox(self.tab_3)
        self.groupBoxCenter.setGeometry(QtCore.QRect(780, 120, 91, 180))
        self.groupBoxCenter.setObjectName("groupBoxCenter")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBoxCenter)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.TCP = QtWidgets.QRadioButton(self.groupBoxCenter)
        self.TCP.setObjectName("TCP")
        self.gridLayout_7.addWidget(self.TCP, 1, 0, 1, 1)
        self.UCD = QtWidgets.QRadioButton(self.groupBoxCenter)
        self.UCD.setObjectName("UCD")
        self.gridLayout_7.addWidget(self.UCD, 0, 0, 1, 1)
        self.BCM = QtWidgets.QRadioButton(self.groupBoxCenter)
        self.BCM.setObjectName("BCM")
        self.gridLayout_7.addWidget(self.BCM, 3, 0, 1, 1)
        self.HAR = QtWidgets.QRadioButton(self.groupBoxCenter)
        self.HAR.setObjectName("HAR")
        self.gridLayout_7.addWidget(self.HAR, 4, 0, 1, 1)
        self.JAX = QtWidgets.QRadioButton(self.groupBoxCenter)
        self.JAX.setObjectName("JAX")
        self.gridLayout_7.addWidget(self.JAX, 5, 0, 1, 1)
        self.CCP = QtWidgets.QRadioButton(self.groupBoxCenter)
        self.CCP.setObjectName("CCP")
        self.gridLayout_7.addWidget(self.CCP, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_10.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1438, 24))
        self.menubar.setObjectName("menubar")
        self.menuMore_Options = QtWidgets.QMenu(self.menubar)
        self.menuMore_Options.setObjectName("menuMore_Options")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionChange_ID = QtWidgets.QAction(MainWindow)
        self.actionChange_ID.setObjectName("actionChange_ID")
        self.actionManually_select_output_folder = QtWidgets.QAction(MainWindow)
        self.actionManually_select_output_folder.setObjectName("actionManually_select_output_folder")
        self.actionAccurate_folder_size_calculation = QtWidgets.QAction(MainWindow)
        self.actionAccurate_folder_size_calculation.setObjectName("actionAccurate_folder_size_calculation")
        self.actionResize = QtWidgets.QAction(MainWindow)
        self.actionResize.setObjectName("actionResize")
        self.actionReset_screen_size = QtWidgets.QAction(MainWindow)
        self.actionReset_screen_size.setObjectName("actionReset_screen_size")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.actionPDF_user_guide = QtWidgets.QAction(MainWindow)
        self.actionPDF_user_guide.setObjectName("actionPDF_user_guide")
        self.actionExample_data = QtWidgets.QAction(MainWindow)
        self.actionExample_data.setObjectName("actionExample_data")
        self.menuMore_Options.addAction(self.actionReset_screen_size)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionPDF_user_guide)
        self.menubar.addAction(self.menuMore_Options.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "HARP", None))
        self.groupBoxModality.setTitle(_translate("MainWindow", "Imaging modality", None))
        self.radioButtonuCT.setText(_translate("MainWindow", "µCT", None))
        self.radioButtonOPT.setText(_translate("MainWindow", "OPT", None))
        self.pushButtonOutput.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Output folder</span></p><p>HARP will suggest a folder called: &quot;processed recon\\name_of_recon&quot;</p><p>If the output folder is not appropiate please select this button and choose a more suitable location</p></body></html>", None))
        self.pushButtonOutput.setText(_translate("MainWindow", "Output folder", None))
        self.pushButtonInput.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Input folder</span></p><p>Choose the folder containing the recon image files.</p><p>HARP will automatically suggest the:</p><p>- Output folder</p><p>- Recon log file</p><p>- Scan folder</p><p>- SPR file</p><p>- imaging modality</p><p>Additional the naming of the file folder will be checked to see if it matches the Harwell IMPC naming criteria. </p></body></html>", None))
        self.pushButtonInput.setText(_translate("MainWindow", "Input folder", None))
        self.pushButtonGo.setText(_translate("MainWindow", "Add to Processing List", None))
        self.groupBoxReconInfo.setTitle(_translate("MainWindow", "Recon file info", None))
        self.labelPixel.setText(_translate("MainWindow", "Pixel size (µm)", None))
        self.lcdNumberPixel.setToolTip(_translate("MainWindow", "This is the pixel size of the original recon", None))
        self.lcdNumberFile.setToolTip(_translate("MainWindow", "This is the approximate folder size of the original recon", None))
        self.labelFile.setText(_translate("MainWindow", "Folder size (Mb)", None))
        self.groupBoxOptions.setTitle(_translate("MainWindow", "Options", None))
        self.radioButtonMan.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Manual</span></p><p>In cases where the automatic crop is not capable of determining the crop dimensions the user can either manually enter the dimensiosn or press the &quot;Get Dimensions&quot; button.</p><p>The &quot;Get dimensions&quot; button provides a Z-projected image of the stack and allows the user to select a cropping region. (see the HARP user guide)</p></body></html>", None))
        self.radioButtonMan.setText(_translate("MainWindow", "Manual", None))
        self.radioButtonAuto.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Automatic cropping</span></p><p>The cropping dimensions will be determined automatically. </p></body></html>", None))
        self.radioButtonAuto.setText(_translate("MainWindow", "Automatic", None))
        self.checkBoxCropYes.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose whether cropping should be perfomed</p></body></html>", None))
        self.checkBoxCropYes.setText(_translate("MainWindow", "Yes", None))
        self.label_3.setText(_translate("MainWindow", "Masking", None))
        self.checkBoxRF.setText(_translate("MainWindow", "Yes", None))
        self.label_2.setText(_translate("MainWindow", "Replace files", None))
        self.checkBoxMovie_2.setText(_translate("MainWindow", "Yes", None))
        self.label.setText(_translate("MainWindow", "Compression", None))
        self.label_13.setText(_translate("MainWindow", "Create movie", None))
        self.checkBoxMask.setText(_translate("MainWindow", "Yes", None))
        self.lineEditH.setText(_translate("MainWindow", "h", None))
        self.lineEditY.setText(_translate("MainWindow", "y", None))
        self.lineEditX.setText(_translate("MainWindow", "x", None))
        self.pushButtonGetDimensions.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Get dimensions</span></p><p>This button provides a Z-projected image of the stack and allows the user to select a cropping region. (see the HARP user guide) </p></body></html>", None))
        self.pushButtonGetDimensions.setText(_translate("MainWindow", "Get dimensions", None))
        self.lineEditW.setText(_translate("MainWindow", "w", None))
        self.label_14.setText(_translate("MainWindow", "Cropping", None))
        self.radioButtonDerived.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Derive dimensions (OPT only)</span></p><p>This option provides additional functionality that for most instances should not be required.</p><p>This option allows dimensions for the crop to be derived from a previous processed channel. </p><p>The channel from which the crop dimensions can be derived can be chosen in the OPT channels section. In the OPT channels section the user should select &quot;Return&quot; on the keyboard on the appropiate channel.</p></body></html>", None))
        self.radioButtonDerived.setText(_translate("MainWindow", "Derive dimensions", None))
        self.radioButtonUseOldCrop.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Use old</span></p><p>reprocess previously cropped slices. This will aplly the latest transforms to the output stacks so that it is in the correct format for submission to  the DCC.</p></body></html>", None))
        self.radioButtonUseOldCrop.setText(_translate("MainWindow", "Use old", None))
        self.lineEditDerivedChnName.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Derive dimensions (OPT only)</span></p><p>This option provides additional functionality that for most instances should not be required.</p><p>This option allows dimensions for the crop to be derived from a previous processed channel. </p><p>The channel from which the crop dimensions can be derived can be chosen in the OPT channels section. In the OPT channels section the user should select &quot;Return&quot; on the keyboard on the appropiate channel.</p></body></html>", None))
        self.checkBoxCropComp.setText(_translate("MainWindow", "Cropped recon", None))
        self.pushButtonIMPC.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">IMPC settings</span></p><p>For upload to the DCC, a compressed NRRD file is required. Click here to autoselect.</p><p><br/></p></body></html>", None))
        self.pushButtonIMPC.setText(_translate("MainWindow", "< IMPC", None))
        self.checkBoxCreateStack.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Create stack</span></p><p>A single stack NRRD/TIFF will be generated at native resolution</p></body></html>", None))
        self.checkBoxCreateStack.setText(_translate("MainWindow", "Single volume", None))
        self.comboBoxStackType.setItemText(0, _translate("MainWindow", "NRRD", None))
        self.comboBoxStackType.setItemText(1, _translate("MainWindow", "TIFF", None))
        self.label_4.setText(_translate("MainWindow", "Pixel size (µm)", None))
        self.checkBoxScansReconComp.setText(_translate("MainWindow", "Scans and original recon", None))
        self.label_5.setText(_translate("MainWindow", "Downsample", None))
        self.checkBoxSF2.setText(_translate("MainWindow", "2", None))
        self.checkBoxSF3.setText(_translate("MainWindow", "3", None))
        self.checkBoxSF4.setText(_translate("MainWindow", "4", None))
        self.checkBoxSF5.setText(_translate("MainWindow", "5", None))
        self.checkBoxSF6.setText(_translate("MainWindow", "6", None))
        item = self.tableWidgetPixelScales.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value", None))
        self.spinPixelSize.setToolTip(_translate("MainWindow", "Select a pixel size to rescale", None))
        self.buttonAddPixelSize.setToolTip(_translate("MainWindow", "Add current pixel size to list", None))
        self.buttonAddPixelSize.setText(_translate("MainWindow", "Add", None))
        self.buttonRemovePixelSize.setText(_translate("MainWindow", "Remove", None))
        self.checkBoxReprocessToRas.setText(_translate("MainWindow", "reprocess to RAS", None))
        self.groupBoxID.setTitle(_translate("MainWindow", "Identification", None))
        self.labelAge.setText(_translate("MainWindow", "Stage", None))
        self.labelDate.setText(_translate("MainWindow", "Date", None))
        self.labelGroup.setText(_translate("MainWindow", "Gene", None))
        self.labelZygosity.setText(_translate("MainWindow", "Zygosity", None))
        self.labelSex.setText(_translate("MainWindow", "Sex", None))
        self.labelChannel.setText(_translate("MainWindow", "Channel", None))
        self.labelLitter.setText(_translate("MainWindow", "Litter", None))
        self.labelName.setText(_translate("MainWindow", "Full name", None))
        self.lineEditName.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Identification</span></p><p>You can update the name of recon here and check to see if it is in the right format. </p><p>Each identifier is separated by a underscore _ </p><p>Any additional info can be stored after &quot;rec&quot;:</p><p>[date]_[gene]_[stage]_[litter]_[zygosity]_[sex]_rec_[any additional info]</p></body></html>", None))
        self.pushButtonUpdate.setText(_translate("MainWindow", "Update", None))
        self.label_7.setText(_translate("MainWindow", "<b>Name format</b>: \n"
"<br>[date]_[gene]_[stage]_[litter]_[zygosity]_[sex]_{channel}_rec \n"
"<br><br><b>Key</b>: \n"
"<br>[ ] = required for µCT and OPT \n"
"<br>{ } = required for OPT only \n"
"<br>ND = Not determined ", None))
        self.label_6.setText(_translate("MainWindow", "<b>Example names (µCT):</b>\n"
"<br>20140211_RIC8B_E18.5_16.4a_HOM_XX_rec\n"
"<br>20140211_RIC8B_E18.5_16.4a_HOM_ND_rec      \n"
"<br><br><b>Example name (OPT):</b>\n"
"<br>20140211_RIC8B_E18.5_16.4a_HOM_XX_UV_rec", None))
        self.groupBoxuCTOnly.setTitle(_translate("MainWindow", "Additional files and folders", None))
        self.pushButtonCTRecon.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Recon log</span></p><p>The recon log is identified automatically but can be selected by the user using this button.</p></body></html>", None))
        self.pushButtonCTRecon.setText(_translate("MainWindow", "Recon log", None))
        self.pushButtonCTSPR.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">SPR</span></p><p>A SPR file is identified automatically but can be selected by the user using this button.</p><p>[NOTE: This may be removed as the information is not essential. All additional files are copied over to the processed recon folder]</p></body></html>", None))
        self.pushButtonCTSPR.setText(_translate("MainWindow", "SPR file", None))
        self.pushButtonScan.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Scan folder</span></p><p>The scan folder is identified automatically but can be selected by the user using this button.</p></body></html>", None))
        self.pushButtonScan.setText(_translate("MainWindow", "Scan folder", None))
        self.groupBoxModality_2.setTitle(_translate("MainWindow", "Status", None))
        self.textEditStatusMessages.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Status</span></p><p><span style=\" font-size:12pt;\">This updates the user about the status of HARP when determining the manual crop dimensions after selecting &quot;Get Dimensions&quot;.</span></p></body></html>", None))
        self.groupBoxOPTChannels.setTitle(_translate("MainWindow", "OPT channels", None))
        item = self.tableWidgetOPT.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidgetOPT.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidgetOPT.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidgetOPT.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidgetOPT.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidgetOPT.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidgetOPT.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidgetOPT.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Channel type", None))
        item = self.tableWidgetOPT.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.tableWidgetOPT.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Processed", None))
        self.checkBoxInd.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Process Individually</span></p><p>By default all OPT channels will be added to the processing list together. </p><p>The crop box dimensions will be determined using the channel currently selected (highlighted red). </p><p><br/></p><p>All other channels will derive their cropping dimensions from the first channel. </p><p>Alternatively if this &quot;Process Individual Box&quot; is pressed the individual channels can be processed individually. The user can then choose the cropping method used for each channel.</p></body></html>", None))
        self.checkBoxInd.setText(_translate("MainWindow", "Process individually", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Parameters", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Input", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Output", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Start Time", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Finish Time", None))
        self.pushButtonStart.setText(_translate("MainWindow", "Start", None))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop", None))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add More", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Processing", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:10pt; font-weight:600;\">File names to ignore</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cantarell\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:10pt;\">The patterns wensure that only recon files get processed and not other generated images. The default settings work for Skyscan xxx</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cantarell\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:10pt;\">Example: &quot;*spr.bmp&quot;  This entry will ensure no files that end in spr.bmp will get processeed</span></p></body></html>", None))
        self.pushButtonSaveOptions.setText(_translate("MainWindow", "save options", None))
        self.pushButtonResetIgnoreFiles.setText(_translate("MainWindow", "reset", None))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:10pt; font-weight:600;\">File names to use</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cantarell\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:10pt;\">The patterns here are used to select files for use in processing. The default settings work for Skyscan xxx</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cantarell\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:10pt;\">Example: &quot;*rec.bmp&quot; </span></p></body></html>", None))
        self.pushButtonResetUSeFiles.setText(_translate("MainWindow", "reset", None))
        self.checkBoxSuppressNameWarnings.setText(_translate("MainWindow", "Supress file name warnings", None))
        self.checkBoxSuppressModalityWarning.setText(_translate("MainWindow", "Supress modality warnings", None))
        self.groupBoxCenter.setTitle(_translate("MainWindow", "Center", None))
        self.TCP.setText(_translate("MainWindow", "TCP", None))
        self.UCD.setText(_translate("MainWindow", "UCD", None))
        self.BCM.setText(_translate("MainWindow", "BCM", None))
        self.HAR.setText(_translate("MainWindow", "HAR", None))
        self.JAX.setText(_translate("MainWindow", "JAX", None))
        self.CCP.setText(_translate("MainWindow", "CCP", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Options", None))
        self.menuMore_Options.setTitle(_translate("MainWindow", "View", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionChange_ID.setText(_translate("MainWindow", "Allow identification to be changed", None))
        self.actionManually_select_output_folder.setText(_translate("MainWindow", "Allow manually selection of output folder", None))
        self.actionAccurate_folder_size_calculation.setText(_translate("MainWindow", "Accurate folder size calculation", None))
        self.actionResize.setText(_translate("MainWindow", "Resize screen for small monitors", None))
        self.actionReset_screen_size.setText(_translate("MainWindow", "Reset screen size", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionManual.setText(_translate("MainWindow", "Contents", None))
        self.actionPDF_user_guide.setText(_translate("MainWindow", "PDF user guide", None))
        self.actionExample_data.setText(_translate("MainWindow", "Import example data", None))

