# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Mon Feb 17 11:01:22 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(329, 364)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.formLayout_2 = QtGui.QFormLayout(self.centralWidget)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lineEditInput = QtGui.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditInput.setFont(font)
        self.lineEditInput.setObjectName(_fromUtf8("lineEditInput"))
        self.gridLayout_5.addWidget(self.lineEditInput, 0, 2, 1, 1)
        self.lineEditOutput = QtGui.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditOutput.setFont(font)
        self.lineEditOutput.setObjectName(_fromUtf8("lineEditOutput"))
        self.gridLayout_5.addWidget(self.lineEditOutput, 1, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.toolButtonOutput = QtGui.QToolButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolButtonOutput.setFont(font)
        self.toolButtonOutput.setObjectName(_fromUtf8("toolButtonOutput"))
        self.gridLayout_5.addWidget(self.toolButtonOutput, 1, 1, 1, 1)
        self.toolButtonInput = QtGui.QToolButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolButtonInput.setFont(font)
        self.toolButtonInput.setObjectName(_fromUtf8("toolButtonInput"))
        self.gridLayout_5.addWidget(self.toolButtonInput, 0, 1, 1, 1)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.LabelRole, self.gridLayout_5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_8 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.lineEditName = QtGui.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditName.setFont(font)
        self.lineEditName.setText(_fromUtf8(""))
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.gridLayout.addWidget(self.lineEditName, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.comboBoxScale = QtGui.QComboBox(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxScale.setFont(font)
        self.comboBoxScale.setObjectName(_fromUtf8("comboBoxScale"))
        self.comboBoxScale.addItem(_fromUtf8(""))
        self.comboBoxScale.addItem(_fromUtf8(""))
        self.comboBoxScale.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxScale, 5, 1, 1, 1)
        self.checkBoxMovie = QtGui.QCheckBox(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxMovie.setFont(font)
        self.checkBoxMovie.setObjectName(_fromUtf8("checkBoxMovie"))
        self.gridLayout.addWidget(self.checkBoxMovie, 7, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 6, 1, 1, 1)
        self.comboBoxCrop = QtGui.QComboBox(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxCrop.setFont(font)
        self.comboBoxCrop.setObjectName(_fromUtf8("comboBoxCrop"))
        self.comboBoxCrop.addItem(_fromUtf8(""))
        self.comboBoxCrop.addItem(_fromUtf8(""))
        self.comboBoxCrop.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxCrop, 4, 1, 1, 1)
        self.pushButtonGo = QtGui.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonGo.setFont(font)
        self.pushButtonGo.setDefault(False)
        self.pushButtonGo.setObjectName(_fromUtf8("pushButtonGo"))
        self.gridLayout.addWidget(self.pushButtonGo, 8, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.formLayout_2.setLayout(3, QtGui.QFormLayout.SpanningRole, self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(2, QtGui.QFormLayout.LabelRole, spacerItem)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 329, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionLoad_settings = QtGui.QAction(MainWindow)
        self.actionLoad_settings.setObjectName(_fromUtf8("actionLoad_settings"))
        self.actionSave_settings = QtGui.QAction(MainWindow)
        self.actionSave_settings.setObjectName(_fromUtf8("actionSave_settings"))
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_settings)
        self.menuFile.addAction(self.actionSave_settings)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SIaH: Image Processing Tool", None))
        self.label_13.setText(_translate("MainWindow", "Input Folder", None))
        self.label_2.setText(_translate("MainWindow", "Output Folder", None))
        self.toolButtonOutput.setText(_translate("MainWindow", "...", None))
        self.toolButtonInput.setText(_translate("MainWindow", "...", None))
        self.label_8.setText(_translate("MainWindow", "Output Name", None))
        self.label_3.setText(_translate("MainWindow", "Cropping", None))
        self.label_4.setText(_translate("MainWindow", "Downsize", None))
        self.comboBoxScale.setItemText(0, _translate("MainWindow", "Automatic", None))
        self.comboBoxScale.setItemText(1, _translate("MainWindow", "Manual", None))
        self.comboBoxScale.setItemText(2, _translate("MainWindow", "No Downsize", None))
        self.checkBoxMovie.setText(_translate("MainWindow", "Yes", None))
        self.label_7.setText(_translate("MainWindow", "Create Movie", None))
        self.label_9.setText(_translate("MainWindow", "Embryo Stage", None))
        self.label_6.setText(_translate("MainWindow", "Reorienate", None))
        self.checkBox.setText(_translate("MainWindow", "Yes", None))
        self.comboBoxCrop.setItemText(0, _translate("MainWindow", "Automatic", None))
        self.comboBoxCrop.setItemText(1, _translate("MainWindow", "Manual", None))
        self.comboBoxCrop.setItemText(2, _translate("MainWindow", "No crop", None))
        self.pushButtonGo.setText(_translate("MainWindow", "Go!", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionLoad_settings.setText(_translate("MainWindow", "Load settings", None))
        self.actionSave_settings.setText(_translate("MainWindow", "Save settings", None))

