# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Mon Feb 17 16:15:46 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(653, 971)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(41, 20, 561, 62))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lineEditInput = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditInput.setFont(font)
        self.lineEditInput.setObjectName(_fromUtf8("lineEditInput"))
        self.gridLayout_5.addWidget(self.lineEditInput, 0, 1, 1, 1)
        self.lineEditOutput = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditOutput.setFont(font)
        self.lineEditOutput.setObjectName(_fromUtf8("lineEditOutput"))
        self.gridLayout_5.addWidget(self.lineEditOutput, 1, 1, 1, 1)
        self.pushButtonInput = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonInput.setFont(font)
        self.pushButtonInput.setObjectName(_fromUtf8("pushButtonInput"))
        self.gridLayout_5.addWidget(self.pushButtonInput, 0, 0, 1, 1)
        self.pushButtonOutput = QtGui.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonOutput.setFont(font)
        self.pushButtonOutput.setObjectName(_fromUtf8("pushButtonOutput"))
        self.gridLayout_5.addWidget(self.pushButtonOutput, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(39, 90, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(9, 30, 82, 17))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_4.setGeometry(QtCore.QRect(119, 30, 82, 17))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(39, 170, 281, 211))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 6, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.comboBoxCrop = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxCrop.setFont(font)
        self.comboBoxCrop.setObjectName(_fromUtf8("comboBoxCrop"))
        self.comboBoxCrop.addItem(_fromUtf8(""))
        self.comboBoxCrop.addItem(_fromUtf8(""))
        self.comboBoxCrop.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxCrop, 4, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.checkBoxMovie = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxMovie.setFont(font)
        self.checkBoxMovie.setObjectName(_fromUtf8("checkBoxMovie"))
        self.gridLayout.addWidget(self.checkBoxMovie, 7, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.lineEditName = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditName.setFont(font)
        self.lineEditName.setText(_fromUtf8(""))
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.gridLayout.addWidget(self.lineEditName, 3, 1, 1, 1)
        self.comboBoxScale = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxScale.setFont(font)
        self.comboBoxScale.setObjectName(_fromUtf8("comboBoxScale"))
        self.comboBoxScale.addItem(_fromUtf8(""))
        self.comboBoxScale.addItem(_fromUtf8(""))
        self.comboBoxScale.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxScale, 5, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(23, 400, 591, 441))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 261, 190))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.checkBox_2 = QtGui.QCheckBox(self.formLayoutWidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox_2)
        self.lineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.pushButton = QtGui.QPushButton(self.formLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButton)
        self.lineEdit_3 = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.pushButton_2 = QtGui.QPushButton(self.formLayoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_2)
        self.lineEdit_4 = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.pushButton_3 = QtGui.QPushButton(self.formLayoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButton_3)
        self.lineEdit_5 = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.pushButton_4 = QtGui.QPushButton(self.formLayoutWidget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButton_4)
        self.lineEdit_6 = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_6)
        self.comboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.comboBox)
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(310, 30, 261, 190))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.formLayoutWidget_2)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox_3)
        self.lineEdit_7 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_7)
        self.pushButton_5 = QtGui.QPushButton(self.formLayoutWidget_2)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButton_5)
        self.lineEdit_8 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_8)
        self.pushButton_6 = QtGui.QPushButton(self.formLayoutWidget_2)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_6)
        self.lineEdit_9 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_9)
        self.pushButton_7 = QtGui.QPushButton(self.formLayoutWidget_2)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButton_7)
        self.lineEdit_10 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_10)
        self.pushButton_8 = QtGui.QPushButton(self.formLayoutWidget_2)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButton_8)
        self.lineEdit_11 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_11)
        self.comboBox_2 = QtGui.QComboBox(self.formLayoutWidget_2)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.comboBox_2)
        self.formLayoutWidget_3 = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 240, 261, 190))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.checkBox_5 = QtGui.QCheckBox(self.formLayoutWidget_3)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox_5)
        self.lineEdit_12 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_12)
        self.pushButton_13 = QtGui.QPushButton(self.formLayoutWidget_3)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButton_13)
        self.lineEdit_13 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_13)
        self.pushButton_14 = QtGui.QPushButton(self.formLayoutWidget_3)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_14)
        self.lineEdit_20 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_20)
        self.pushButton_15 = QtGui.QPushButton(self.formLayoutWidget_3)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButton_15)
        self.lineEdit_21 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_21)
        self.pushButton_16 = QtGui.QPushButton(self.formLayoutWidget_3)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButton_16)
        self.lineEdit_22 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_22)
        self.comboBox_4 = QtGui.QComboBox(self.formLayoutWidget_3)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.comboBox_4)
        self.formLayoutWidget_4 = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(310, 240, 261, 190))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.checkBox_6 = QtGui.QCheckBox(self.formLayoutWidget_4)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox_6)
        self.lineEdit_23 = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_23)
        self.pushButton_17 = QtGui.QPushButton(self.formLayoutWidget_4)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButton_17)
        self.lineEdit_24 = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_24)
        self.pushButton_18 = QtGui.QPushButton(self.formLayoutWidget_4)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_18)
        self.lineEdit_25 = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_25)
        self.pushButton_19 = QtGui.QPushButton(self.formLayoutWidget_4)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButton_19)
        self.lineEdit_26 = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_26)
        self.pushButton_20 = QtGui.QPushButton(self.formLayoutWidget_4)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButton_20)
        self.lineEdit_27 = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_27)
        self.comboBox_5 = QtGui.QComboBox(self.formLayoutWidget_4)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.LabelRole, self.comboBox_5)
        self.pushButtonGo = QtGui.QPushButton(self.centralwidget)
        self.pushButtonGo.setGeometry(QtCore.QRect(180, 850, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonGo.setFont(font)
        self.pushButtonGo.setDefault(False)
        self.pushButtonGo.setObjectName(_fromUtf8("pushButtonGo"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 653, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "SIaH: Image Processor", None))
        self.pushButtonInput.setText(_translate("MainWindow", "Input folder", None))
        self.pushButtonOutput.setText(_translate("MainWindow", "Output folder", None))
        self.groupBox.setTitle(_translate("MainWindow", "Imaging modality used", None))
        self.radioButton_3.setText(_translate("MainWindow", "µCT", None))
        self.radioButton_4.setText(_translate("MainWindow", "OPT", None))
        self.checkBox.setText(_translate("MainWindow", "Yes", None))
        self.label_8.setText(_translate("MainWindow", "Output name", None))
        self.comboBoxCrop.setItemText(0, _translate("MainWindow", "Automatic", None))
        self.comboBoxCrop.setItemText(1, _translate("MainWindow", "Manual", None))
        self.comboBoxCrop.setItemText(2, _translate("MainWindow", "No crop", None))
        self.label_3.setText(_translate("MainWindow", "Cropping", None))
        self.label_9.setText(_translate("MainWindow", "Embryo stage", None))
        self.label_4.setText(_translate("MainWindow", "Downsize", None))
        self.checkBoxMovie.setText(_translate("MainWindow", "Yes", None))
        self.label_6.setText(_translate("MainWindow", "Reorientate", None))
        self.comboBoxScale.setItemText(0, _translate("MainWindow", "Automatic", None))
        self.comboBoxScale.setItemText(1, _translate("MainWindow", "Manual", None))
        self.comboBoxScale.setItemText(2, _translate("MainWindow", "No Downsize", None))
        self.label_7.setText(_translate("MainWindow", "Create movie", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "OPT only", None))
        self.checkBox_2.setText(_translate("MainWindow", "Channel 1", None))
        self.pushButton.setText(_translate("MainWindow", "Pick recon log", None))
        self.pushButton_2.setText(_translate("MainWindow", "Pick viewEND", None))
        self.pushButton_3.setText(_translate("MainWindow", "Pick SPR", None))
        self.pushButton_4.setText(_translate("MainWindow", "Pick ARC", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Ch-MPH", None))
        self.checkBox_3.setText(_translate("MainWindow", "Channel 2", None))
        self.pushButton_5.setText(_translate("MainWindow", "Pick recon log", None))
        self.pushButton_6.setText(_translate("MainWindow", "Pick viewEND", None))
        self.pushButton_7.setText(_translate("MainWindow", "Pick SPR", None))
        self.pushButton_8.setText(_translate("MainWindow", "Pick ARC", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Ch-MPH", None))
        self.checkBox_5.setText(_translate("MainWindow", "Channel 3", None))
        self.pushButton_13.setText(_translate("MainWindow", "Pick recon log", None))
        self.pushButton_14.setText(_translate("MainWindow", "Pick viewEND", None))
        self.pushButton_15.setText(_translate("MainWindow", "Pick SPR", None))
        self.pushButton_16.setText(_translate("MainWindow", "Pick ARC", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Ch-MPH", None))
        self.checkBox_6.setText(_translate("MainWindow", "Channel 4", None))
        self.pushButton_17.setText(_translate("MainWindow", "Pick recon log", None))
        self.pushButton_18.setText(_translate("MainWindow", "Pick viewEND", None))
        self.pushButton_19.setText(_translate("MainWindow", "Pick SPR", None))
        self.pushButton_20.setText(_translate("MainWindow", "Pick ARC", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Ch-MPH", None))
        self.pushButtonGo.setText(_translate("MainWindow", "Go!", None))

