#!/usr/bin/python
# Import PyQT module
from PyQt4 import QtGui
# Import MainWindow class from QT Designer
from Progress import *
import sys

# Basically extend the QMainWindow class generated by QT Designer
class Progress(QtGui.QDialog):
    # Create a constructor
    def __init__(self):
       super(Progress, self).__init__()
       self.ui=Ui_Progress()
       self.ui.setupUi(self)
       self.show()

def main():
    app = QtGui.QApplication(sys.argv)
    ex = Progress()
    sys.exit(app.exec_())

if __name__ == "__main__":
    main()